// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response/group/group_join_questions_with_version.proto

package im.turms.turms.pojo.response;

public final class GroupJoinQuestionsWithVersionOuterClass {
  private GroupJoinQuestionsWithVersionOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_turms_proto_GroupJoinQuestionsWithVersion_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_turms_proto_GroupJoinQuestionsWithVersion_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n6response/group/group_join_questions_wi" +
      "th_version.proto\022\016im.turms.proto\032\036google" +
      "/protobuf/wrappers.proto\032#dto/group/grou" +
      "p_join_question.proto\"\230\001\n\035GroupJoinQuest" +
      "ionsWithVersion\022?\n\024group_join_questions\030" +
      "\001 \003(\0132!.im.turms.proto.GroupJoinQuestion" +
      "\0226\n\021last_updated_date\030\002 \001(\0132\033.google.pro" +
      "tobuf.Int64ValueB \n\034im.turms.turms.pojo." +
      "responseP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          im.turms.turms.pojo.dto.GroupJoinQuestionOuterClass.getDescriptor(),
        });
    internal_static_im_turms_proto_GroupJoinQuestionsWithVersion_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_im_turms_proto_GroupJoinQuestionsWithVersion_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_turms_proto_GroupJoinQuestionsWithVersion_descriptor,
        new java.lang.String[] { "GroupJoinQuestions", "LastUpdatedDate", });
    com.google.protobuf.WrappersProto.getDescriptor();
    im.turms.turms.pojo.dto.GroupJoinQuestionOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
