// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response/group/group_invitations_with_version.proto

package im.turms.turms.pojo.response;

public interface GroupInvitationsWithVersionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:im.turms.proto.GroupInvitationsWithVersion)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .im.turms.proto.GroupInvitation group_invitations = 1;</code>
   */
  java.util.List<im.turms.turms.pojo.dto.GroupInvitation> 
      getGroupInvitationsList();
  /**
   * <code>repeated .im.turms.proto.GroupInvitation group_invitations = 1;</code>
   */
  im.turms.turms.pojo.dto.GroupInvitation getGroupInvitations(int index);
  /**
   * <code>repeated .im.turms.proto.GroupInvitation group_invitations = 1;</code>
   */
  int getGroupInvitationsCount();
  /**
   * <code>repeated .im.turms.proto.GroupInvitation group_invitations = 1;</code>
   */
  java.util.List<? extends im.turms.turms.pojo.dto.GroupInvitationOrBuilder> 
      getGroupInvitationsOrBuilderList();
  /**
   * <code>repeated .im.turms.proto.GroupInvitation group_invitations = 1;</code>
   */
  im.turms.turms.pojo.dto.GroupInvitationOrBuilder getGroupInvitationsOrBuilder(
      int index);

  /**
   * <code>.google.protobuf.Int64Value last_updated_date = 2;</code>
   * @return Whether the lastUpdatedDate field is set.
   */
  boolean hasLastUpdatedDate();
  /**
   * <code>.google.protobuf.Int64Value last_updated_date = 2;</code>
   * @return The lastUpdatedDate.
   */
  com.google.protobuf.Int64Value getLastUpdatedDate();
  /**
   * <code>.google.protobuf.Int64Value last_updated_date = 2;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getLastUpdatedDateOrBuilder();
}
