// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response/group/groups_with_version.proto

package im.turms.turms.pojo.response;

public final class GroupsWithVersionOuterClass {
  private GroupsWithVersionOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_turms_proto_GroupsWithVersion_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_turms_proto_GroupsWithVersion_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(response/group/groups_with_version.pro" +
      "to\022\016im.turms.proto\032\036google/protobuf/wrap" +
      "pers.proto\032\025dto/group/group.proto\"r\n\021Gro" +
      "upsWithVersion\022%\n\006groups\030\001 \003(\0132\025.im.turm" +
      "s.proto.Group\0226\n\021last_updated_date\030\002 \001(\013" +
      "2\033.google.protobuf.Int64ValueB \n\034im.turm" +
      "s.turms.pojo.responseP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          im.turms.turms.pojo.dto.GroupOuterClass.getDescriptor(),
        });
    internal_static_im_turms_proto_GroupsWithVersion_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_im_turms_proto_GroupsWithVersion_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_turms_proto_GroupsWithVersion_descriptor,
        new java.lang.String[] { "Groups", "LastUpdatedDate", });
    com.google.protobuf.WrappersProto.getDescriptor();
    im.turms.turms.pojo.dto.GroupOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
