// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response/group/group_members_with_version.proto

package im.turms.turms.pojo.response;

public final class GroupMembersWithVersionOuterClass {
  private GroupMembersWithVersionOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_turms_proto_GroupMembersWithVersion_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_turms_proto_GroupMembersWithVersion_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n/response/group/group_members_with_vers" +
      "ion.proto\022\016im.turms.proto\032\036google/protob" +
      "uf/wrappers.proto\032\034dto/group/group_membe" +
      "r.proto\"\205\001\n\027GroupMembersWithVersion\0222\n\rg" +
      "roup_members\030\001 \003(\0132\033.im.turms.proto.Grou" +
      "pMember\0226\n\021last_updated_date\030\002 \001(\0132\033.goo" +
      "gle.protobuf.Int64ValueB \n\034im.turms.turm" +
      "s.pojo.responseP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          im.turms.turms.pojo.dto.GroupMemberOuterClass.getDescriptor(),
        });
    internal_static_im_turms_proto_GroupMembersWithVersion_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_im_turms_proto_GroupMembersWithVersion_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_turms_proto_GroupMembersWithVersion_descriptor,
        new java.lang.String[] { "GroupMembers", "LastUpdatedDate", });
    com.google.protobuf.WrappersProto.getDescriptor();
    im.turms.turms.pojo.dto.GroupMemberOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
