// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response/group/group_join_requests_with_version.proto

package im.turms.turms.pojo.response;

public final class GroupJoinRequestsWithVersionOuterClass {
  private GroupJoinRequestsWithVersionOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_turms_proto_GroupJoinRequestsWithVersion_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_turms_proto_GroupJoinRequestsWithVersion_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n5response/group/group_join_requests_wit" +
      "h_version.proto\022\016im.turms.proto\032\036google/" +
      "protobuf/wrappers.proto\032\"dto/group/group" +
      "_join_request.proto\"\225\001\n\034GroupJoinRequest" +
      "sWithVersion\022=\n\023group_join_requests\030\001 \003(" +
      "\0132 .im.turms.proto.GroupJoinRequest\0226\n\021l" +
      "ast_updated_date\030\002 \001(\0132\033.google.protobuf" +
      ".Int64ValueB \n\034im.turms.turms.pojo.respo" +
      "nseP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          im.turms.turms.pojo.dto.GroupJoinRequestOuterClass.getDescriptor(),
        });
    internal_static_im_turms_proto_GroupJoinRequestsWithVersion_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_im_turms_proto_GroupJoinRequestsWithVersion_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_turms_proto_GroupJoinRequestsWithVersion_descriptor,
        new java.lang.String[] { "GroupJoinRequests", "LastUpdatedDate", });
    com.google.protobuf.WrappersProto.getDescriptor();
    im.turms.turms.pojo.dto.GroupJoinRequestOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
