// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response/message/messages_with_total_list.proto

package im.turms.turms.pojo.response;

public final class MessagesWithTotalListOuterClass {
  private MessagesWithTotalListOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_turms_proto_MessagesWithTotalList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_turms_proto_MessagesWithTotalList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n/response/message/messages_with_total_l" +
      "ist.proto\022\016im.turms.proto\032%dto/message/m" +
      "essages_with_total.proto\"\\\n\025MessagesWith" +
      "TotalList\022C\n\030messages_with_total_list\030\001 " +
      "\003(\0132!.im.turms.proto.MessagesWithTotalB " +
      "\n\034im.turms.turms.pojo.responseP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          im.turms.turms.pojo.dto.MessagesWithTotalOuterClass.getDescriptor(),
        });
    internal_static_im_turms_proto_MessagesWithTotalList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_im_turms_proto_MessagesWithTotalList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_turms_proto_MessagesWithTotalList_descriptor,
        new java.lang.String[] { "MessagesWithTotalList", });
    im.turms.turms.pojo.dto.MessagesWithTotalOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
