// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response/message/message_statuses.proto

package im.turms.turms.pojo.response;

public interface MessageStatusesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:im.turms.proto.MessageStatuses)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .im.turms.proto.MessageStatus message_statuses = 1;</code>
   */
  java.util.List<im.turms.turms.pojo.dto.MessageStatus> 
      getMessageStatusesList();
  /**
   * <code>repeated .im.turms.proto.MessageStatus message_statuses = 1;</code>
   */
  im.turms.turms.pojo.dto.MessageStatus getMessageStatuses(int index);
  /**
   * <code>repeated .im.turms.proto.MessageStatus message_statuses = 1;</code>
   */
  int getMessageStatusesCount();
  /**
   * <code>repeated .im.turms.proto.MessageStatus message_statuses = 1;</code>
   */
  java.util.List<? extends im.turms.turms.pojo.dto.MessageStatusOrBuilder> 
      getMessageStatusesOrBuilderList();
  /**
   * <code>repeated .im.turms.proto.MessageStatus message_statuses = 1;</code>
   */
  im.turms.turms.pojo.dto.MessageStatusOrBuilder getMessageStatusesOrBuilder(
      int index);
}
