// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response/message/messages_with_total_list.proto

package im.turms.turms.pojo.response;

public interface MessagesWithTotalListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:im.turms.proto.MessagesWithTotalList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .im.turms.proto.MessagesWithTotal messages_with_total_list = 1;</code>
   */
  java.util.List<im.turms.turms.pojo.dto.MessagesWithTotal> 
      getMessagesWithTotalListList();
  /**
   * <code>repeated .im.turms.proto.MessagesWithTotal messages_with_total_list = 1;</code>
   */
  im.turms.turms.pojo.dto.MessagesWithTotal getMessagesWithTotalList(int index);
  /**
   * <code>repeated .im.turms.proto.MessagesWithTotal messages_with_total_list = 1;</code>
   */
  int getMessagesWithTotalListCount();
  /**
   * <code>repeated .im.turms.proto.MessagesWithTotal messages_with_total_list = 1;</code>
   */
  java.util.List<? extends im.turms.turms.pojo.dto.MessagesWithTotalOrBuilder> 
      getMessagesWithTotalListOrBuilderList();
  /**
   * <code>repeated .im.turms.proto.MessagesWithTotal messages_with_total_list = 1;</code>
   */
  im.turms.turms.pojo.dto.MessagesWithTotalOrBuilder getMessagesWithTotalListOrBuilder(
      int index);
}
