// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response/message/messages.proto

package im.turms.turms.pojo.response;

public interface MessagesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:im.turms.proto.Messages)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .im.turms.proto.Message messages = 1;</code>
   */
  java.util.List<im.turms.turms.pojo.dto.Message> 
      getMessagesList();
  /**
   * <code>repeated .im.turms.proto.Message messages = 1;</code>
   */
  im.turms.turms.pojo.dto.Message getMessages(int index);
  /**
   * <code>repeated .im.turms.proto.Message messages = 1;</code>
   */
  int getMessagesCount();
  /**
   * <code>repeated .im.turms.proto.Message messages = 1;</code>
   */
  java.util.List<? extends im.turms.turms.pojo.dto.MessageOrBuilder> 
      getMessagesOrBuilderList();
  /**
   * <code>repeated .im.turms.proto.Message messages = 1;</code>
   */
  im.turms.turms.pojo.dto.MessageOrBuilder getMessagesOrBuilder(
      int index);
}
