// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response/turms_response.proto

package im.turms.turms.pojo.response;

public interface TurmsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:im.turms.proto.TurmsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Note: request_id is allowed to be duplicated because
   * it is used for clients to identify the response of the same request id in a session
   * </pre>
   *
   * <code>int64 request_id = 1;</code>
   * @return The requestId.
   */
  long getRequestId();

  /**
   * <code>int32 code = 2;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>.google.protobuf.StringValue reason = 3;</code>
   * @return Whether the reason field is set.
   */
  boolean hasReason();
  /**
   * <code>.google.protobuf.StringValue reason = 3;</code>
   * @return The reason.
   */
  com.google.protobuf.StringValue getReason();
  /**
   * <code>.google.protobuf.StringValue reason = 3;</code>
   */
  com.google.protobuf.StringValueOrBuilder getReasonOrBuilder();

  /**
   * <code>.im.turms.proto.TurmsResponse.Data data = 4;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.im.turms.proto.TurmsResponse.Data data = 4;</code>
   * @return The data.
   */
  im.turms.turms.pojo.response.TurmsResponse.Data getData();
  /**
   * <code>.im.turms.proto.TurmsResponse.Data data = 4;</code>
   */
  im.turms.turms.pojo.response.TurmsResponse.DataOrBuilder getDataOrBuilder();

  /**
   * <code>.im.turms.proto.TurmsRequest notification = 5;</code>
   * @return Whether the notification field is set.
   */
  boolean hasNotification();
  /**
   * <code>.im.turms.proto.TurmsRequest notification = 5;</code>
   * @return The notification.
   */
  im.turms.turms.pojo.request.TurmsRequest getNotification();
  /**
   * <code>.im.turms.proto.TurmsRequest notification = 5;</code>
   */
  im.turms.turms.pojo.request.TurmsRequestOrBuilder getNotificationOrBuilder();
}
