// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response/turms_response.proto

package im.turms.turms.pojo.response;

public final class TurmsResponseOuterClass {
  private TurmsResponseOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_turms_proto_TurmsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_turms_proto_TurmsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_turms_proto_TurmsResponse_Data_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_turms_proto_TurmsResponse_Data_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035response/turms_response.proto\022\016im.turm" +
      "s.proto\032\036google/protobuf/wrappers.proto\032" +
      "\034dto/signal/acknowledge.proto\032 dto/messa" +
      "ge/message_status.proto\032\033request/turms_r" +
      "equest.proto\032\"response/common/int64_valu" +
      "es.proto\032/response/common/int64_values_w" +
      "ith_version.proto\0323response/group/group_" +
      "invitations_with_version.proto\0326response" +
      "/group/group_join_questions_with_version" +
      ".proto\0325response/group/group_join_reques" +
      "ts_with_version.proto\032/response/group/gr" +
      "oup_members_with_version.proto\032(response" +
      "/group/groups_with_version.proto\032\037respon" +
      "se/message/messages.proto\032/response/mess" +
      "age/messages_with_total_list.proto\0325resp" +
      "onse/user/user_friend_requests_with_vers" +
      "ion.proto\0329response/user/user_relationsh" +
      "ip_groups_with_version.proto\0323response/u" +
      "ser/user_relationships_with_version.prot" +
      "o\032,response/user/users_infos_with_versio" +
      "n.proto\032)response/user/users_online_stat" +
      "uses.proto\"\243\013\n\rTurmsResponse\022\022\n\nrequest_" +
      "id\030\001 \001(\003\022\014\n\004code\030\002 \001(\005\022,\n\006reason\030\003 \001(\0132\034" +
      ".google.protobuf.StringValue\0220\n\004data\030\004 \001" +
      "(\0132\".im.turms.proto.TurmsResponse.Data\0222" +
      "\n\014notification\030\005 \001(\0132\034.im.turms.proto.Tu" +
      "rmsRequest\032\333\t\n\004Data\022*\n\003ids\030\001 \001(\0132\033.im.tu" +
      "rms.proto.Int64ValuesH\000\022B\n\020ids_with_vers" +
      "ion\030\002 \001(\0132&.im.turms.proto.Int64ValuesWi" +
      "thVersionH\000\022-\n\007success\030\003 \001(\0132\032.google.pr" +
      "otobuf.BoolValueH\000\0222\n\013acknowledge\030\004 \001(\0132" +
      "\033.im.turms.proto.AcknowledgeH\000\022,\n\010messag" +
      "es\030\005 \001(\0132\030.im.turms.proto.MessagesH\000\0227\n\016" +
      "message_status\030\006 \001(\0132\035.im.turms.proto.Me" +
      "ssageStatusH\000\022I\n\030messages_with_total_lis" +
      "t\030\007 \001(\0132%.im.turms.proto.MessagesWithTot" +
      "alListH\000\022I\n\030users_infos_with_version\030\010 \001" +
      "(\0132%.im.turms.proto.UsersInfosWithVersio" +
      "nH\000\022D\n\025users_online_statuses\030\t \001(\0132#.im." +
      "turms.proto.UsersOnlineStatusesH\000\022Z\n!use" +
      "r_friend_requests_with_version\030\n \001(\0132-.i" +
      "m.turms.proto.UserFriendRequestsWithVers" +
      "ionH\000\022b\n%user_relationship_groups_with_v" +
      "ersion\030\013 \001(\01321.im.turms.proto.UserRelati" +
      "onshipGroupsWithVersionH\000\022W\n\037user_relati" +
      "onships_with_version\030\014 \001(\0132,.im.turms.pr" +
      "oto.UserRelationshipsWithVersionH\000\022U\n\036gr" +
      "oup_invitations_with_version\030\r \001(\0132+.im." +
      "turms.proto.GroupInvitationsWithVersionH" +
      "\000\022X\n group_join_requests_with_version\030\016 " +
      "\001(\0132,.im.turms.proto.GroupJoinRequestsWi" +
      "thVersionH\000\022Z\n!group_join_questions_with" +
      "_version\030\017 \001(\0132-.im.turms.proto.GroupJoi" +
      "nQuestionsWithVersionH\000\022M\n\032group_members" +
      "_with_version\030\020 \001(\0132\'.im.turms.proto.Gro" +
      "upMembersWithVersionH\000\022@\n\023groups_with_ve" +
      "rsion\030\021 \001(\0132!.im.turms.proto.GroupsWithV" +
      "ersionH\000B\006\n\004kindB \n\034im.turms.turms.pojo." +
      "responseP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          im.turms.turms.pojo.dto.AcknowledgeOuterClass.getDescriptor(),
          im.turms.turms.pojo.dto.MessageStatusOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.TurmsRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.response.Int64ValuesOuterClass.getDescriptor(),
          im.turms.turms.pojo.response.Int64ValuesWithVersionOuterClass.getDescriptor(),
          im.turms.turms.pojo.response.GroupInvitationsWithVersionOuterClass.getDescriptor(),
          im.turms.turms.pojo.response.GroupJoinQuestionsWithVersionOuterClass.getDescriptor(),
          im.turms.turms.pojo.response.GroupJoinRequestsWithVersionOuterClass.getDescriptor(),
          im.turms.turms.pojo.response.GroupMembersWithVersionOuterClass.getDescriptor(),
          im.turms.turms.pojo.response.GroupsWithVersionOuterClass.getDescriptor(),
          im.turms.turms.pojo.response.MessagesOuterClass.getDescriptor(),
          im.turms.turms.pojo.response.MessagesWithTotalListOuterClass.getDescriptor(),
          im.turms.turms.pojo.response.UserFriendRequestsWithVersionOuterClass.getDescriptor(),
          im.turms.turms.pojo.response.UserRelationshipGroupsWithVersionOuterClass.getDescriptor(),
          im.turms.turms.pojo.response.UserRelationshipsWithVersionOuterClass.getDescriptor(),
          im.turms.turms.pojo.response.UsersInfosWithVersionOuterClass.getDescriptor(),
          im.turms.turms.pojo.response.UsersOnlineStatusesOuterClass.getDescriptor(),
        });
    internal_static_im_turms_proto_TurmsResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_im_turms_proto_TurmsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_turms_proto_TurmsResponse_descriptor,
        new java.lang.String[] { "RequestId", "Code", "Reason", "Data", "Notification", });
    internal_static_im_turms_proto_TurmsResponse_Data_descriptor =
      internal_static_im_turms_proto_TurmsResponse_descriptor.getNestedTypes().get(0);
    internal_static_im_turms_proto_TurmsResponse_Data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_turms_proto_TurmsResponse_Data_descriptor,
        new java.lang.String[] { "Ids", "IdsWithVersion", "Success", "Acknowledge", "Messages", "MessageStatus", "MessagesWithTotalList", "UsersInfosWithVersion", "UsersOnlineStatuses", "UserFriendRequestsWithVersion", "UserRelationshipGroupsWithVersion", "UserRelationshipsWithVersion", "GroupInvitationsWithVersion", "GroupJoinRequestsWithVersion", "GroupJoinQuestionsWithVersion", "GroupMembersWithVersion", "GroupsWithVersion", "Kind", });
    com.google.protobuf.WrappersProto.getDescriptor();
    im.turms.turms.pojo.dto.AcknowledgeOuterClass.getDescriptor();
    im.turms.turms.pojo.dto.MessageStatusOuterClass.getDescriptor();
    im.turms.turms.pojo.request.TurmsRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.response.Int64ValuesOuterClass.getDescriptor();
    im.turms.turms.pojo.response.Int64ValuesWithVersionOuterClass.getDescriptor();
    im.turms.turms.pojo.response.GroupInvitationsWithVersionOuterClass.getDescriptor();
    im.turms.turms.pojo.response.GroupJoinQuestionsWithVersionOuterClass.getDescriptor();
    im.turms.turms.pojo.response.GroupJoinRequestsWithVersionOuterClass.getDescriptor();
    im.turms.turms.pojo.response.GroupMembersWithVersionOuterClass.getDescriptor();
    im.turms.turms.pojo.response.GroupsWithVersionOuterClass.getDescriptor();
    im.turms.turms.pojo.response.MessagesOuterClass.getDescriptor();
    im.turms.turms.pojo.response.MessagesWithTotalListOuterClass.getDescriptor();
    im.turms.turms.pojo.response.UserFriendRequestsWithVersionOuterClass.getDescriptor();
    im.turms.turms.pojo.response.UserRelationshipGroupsWithVersionOuterClass.getDescriptor();
    im.turms.turms.pojo.response.UserRelationshipsWithVersionOuterClass.getDescriptor();
    im.turms.turms.pojo.response.UsersInfosWithVersionOuterClass.getDescriptor();
    im.turms.turms.pojo.response.UsersOnlineStatusesOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
