// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response/user/users_online_statuses.proto

package im.turms.turms.pojo.response;

public interface UsersOnlineStatusesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:im.turms.proto.UsersOnlineStatuses)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .im.turms.proto.UserStatusDetail user_statuses = 1;</code>
   */
  java.util.List<im.turms.turms.pojo.dto.UserStatusDetail> 
      getUserStatusesList();
  /**
   * <code>repeated .im.turms.proto.UserStatusDetail user_statuses = 1;</code>
   */
  im.turms.turms.pojo.dto.UserStatusDetail getUserStatuses(int index);
  /**
   * <code>repeated .im.turms.proto.UserStatusDetail user_statuses = 1;</code>
   */
  int getUserStatusesCount();
  /**
   * <code>repeated .im.turms.proto.UserStatusDetail user_statuses = 1;</code>
   */
  java.util.List<? extends im.turms.turms.pojo.dto.UserStatusDetailOrBuilder> 
      getUserStatusesOrBuilderList();
  /**
   * <code>repeated .im.turms.proto.UserStatusDetail user_statuses = 1;</code>
   */
  im.turms.turms.pojo.dto.UserStatusDetailOrBuilder getUserStatusesOrBuilder(
      int index);
}
