// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response/user/users_online_statuses.proto

package im.turms.turms.pojo.response;

public final class UsersOnlineStatusesOuterClass {
  private UsersOnlineStatusesOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_turms_proto_UsersOnlineStatuses_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_turms_proto_UsersOnlineStatuses_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)response/user/users_online_statuses.pr" +
      "oto\022\016im.turms.proto\032!dto/user/user_statu" +
      "s_detail.proto\"N\n\023UsersOnlineStatuses\0227\n" +
      "\ruser_statuses\030\001 \003(\0132 .im.turms.proto.Us" +
      "erStatusDetailB \n\034im.turms.turms.pojo.re" +
      "sponseP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          im.turms.turms.pojo.dto.UserStatusDetailOuterClass.getDescriptor(),
        });
    internal_static_im_turms_proto_UsersOnlineStatuses_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_im_turms_proto_UsersOnlineStatuses_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_turms_proto_UsersOnlineStatuses_descriptor,
        new java.lang.String[] { "UserStatuses", });
    im.turms.turms.pojo.dto.UserStatusDetailOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
