// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response/user/users_infos_with_version.proto

package im.turms.turms.pojo.response;

public interface UsersInfosWithVersionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:im.turms.proto.UsersInfosWithVersion)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .im.turms.proto.UserInfo user_infos = 1;</code>
   */
  java.util.List<im.turms.turms.pojo.dto.UserInfo> 
      getUserInfosList();
  /**
   * <code>repeated .im.turms.proto.UserInfo user_infos = 1;</code>
   */
  im.turms.turms.pojo.dto.UserInfo getUserInfos(int index);
  /**
   * <code>repeated .im.turms.proto.UserInfo user_infos = 1;</code>
   */
  int getUserInfosCount();
  /**
   * <code>repeated .im.turms.proto.UserInfo user_infos = 1;</code>
   */
  java.util.List<? extends im.turms.turms.pojo.dto.UserInfoOrBuilder> 
      getUserInfosOrBuilderList();
  /**
   * <code>repeated .im.turms.proto.UserInfo user_infos = 1;</code>
   */
  im.turms.turms.pojo.dto.UserInfoOrBuilder getUserInfosOrBuilder(
      int index);

  /**
   * <code>.google.protobuf.Int64Value last_updated_date = 2;</code>
   * @return Whether the lastUpdatedDate field is set.
   */
  boolean hasLastUpdatedDate();
  /**
   * <code>.google.protobuf.Int64Value last_updated_date = 2;</code>
   * @return The lastUpdatedDate.
   */
  com.google.protobuf.Int64Value getLastUpdatedDate();
  /**
   * <code>.google.protobuf.Int64Value last_updated_date = 2;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getLastUpdatedDateOrBuilder();
}
