// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response/user/user_friend_requests_with_version.proto

package im.turms.turms.pojo.response;

public interface UserFriendRequestsWithVersionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:im.turms.proto.UserFriendRequestsWithVersion)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .im.turms.proto.UserFriendRequest user_friend_requests = 1;</code>
   */
  java.util.List<im.turms.turms.pojo.dto.UserFriendRequest> 
      getUserFriendRequestsList();
  /**
   * <code>repeated .im.turms.proto.UserFriendRequest user_friend_requests = 1;</code>
   */
  im.turms.turms.pojo.dto.UserFriendRequest getUserFriendRequests(int index);
  /**
   * <code>repeated .im.turms.proto.UserFriendRequest user_friend_requests = 1;</code>
   */
  int getUserFriendRequestsCount();
  /**
   * <code>repeated .im.turms.proto.UserFriendRequest user_friend_requests = 1;</code>
   */
  java.util.List<? extends im.turms.turms.pojo.dto.UserFriendRequestOrBuilder> 
      getUserFriendRequestsOrBuilderList();
  /**
   * <code>repeated .im.turms.proto.UserFriendRequest user_friend_requests = 1;</code>
   */
  im.turms.turms.pojo.dto.UserFriendRequestOrBuilder getUserFriendRequestsOrBuilder(
      int index);

  /**
   * <code>.google.protobuf.Int64Value last_updated_date = 2;</code>
   * @return Whether the lastUpdatedDate field is set.
   */
  boolean hasLastUpdatedDate();
  /**
   * <code>.google.protobuf.Int64Value last_updated_date = 2;</code>
   * @return The lastUpdatedDate.
   */
  com.google.protobuf.Int64Value getLastUpdatedDate();
  /**
   * <code>.google.protobuf.Int64Value last_updated_date = 2;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getLastUpdatedDateOrBuilder();
}
