// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response/user/user_relationship_groups_with_version.proto

package im.turms.turms.pojo.response;

public interface UserRelationshipGroupsWithVersionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:im.turms.proto.UserRelationshipGroupsWithVersion)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .im.turms.proto.UserRelationshipGroup user_relationship_groups = 1;</code>
   */
  java.util.List<im.turms.turms.pojo.dto.UserRelationshipGroup> 
      getUserRelationshipGroupsList();
  /**
   * <code>repeated .im.turms.proto.UserRelationshipGroup user_relationship_groups = 1;</code>
   */
  im.turms.turms.pojo.dto.UserRelationshipGroup getUserRelationshipGroups(int index);
  /**
   * <code>repeated .im.turms.proto.UserRelationshipGroup user_relationship_groups = 1;</code>
   */
  int getUserRelationshipGroupsCount();
  /**
   * <code>repeated .im.turms.proto.UserRelationshipGroup user_relationship_groups = 1;</code>
   */
  java.util.List<? extends im.turms.turms.pojo.dto.UserRelationshipGroupOrBuilder> 
      getUserRelationshipGroupsOrBuilderList();
  /**
   * <code>repeated .im.turms.proto.UserRelationshipGroup user_relationship_groups = 1;</code>
   */
  im.turms.turms.pojo.dto.UserRelationshipGroupOrBuilder getUserRelationshipGroupsOrBuilder(
      int index);

  /**
   * <code>.google.protobuf.Int64Value last_updated_date = 2;</code>
   * @return Whether the lastUpdatedDate field is set.
   */
  boolean hasLastUpdatedDate();
  /**
   * <code>.google.protobuf.Int64Value last_updated_date = 2;</code>
   * @return The lastUpdatedDate.
   */
  com.google.protobuf.Int64Value getLastUpdatedDate();
  /**
   * <code>.google.protobuf.Int64Value last_updated_date = 2;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getLastUpdatedDateOrBuilder();
}
