// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response/user/users_infos_with_version.proto

package im.turms.turms.pojo.response;

public final class UsersInfosWithVersionOuterClass {
  private UsersInfosWithVersionOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_turms_proto_UsersInfosWithVersion_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_turms_proto_UsersInfosWithVersion_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,response/user/users_infos_with_version" +
      ".proto\022\016im.turms.proto\032\036google/protobuf/" +
      "wrappers.proto\032\030dto/user/user_info.proto" +
      "\"}\n\025UsersInfosWithVersion\022,\n\nuser_infos\030" +
      "\001 \003(\0132\030.im.turms.proto.UserInfo\0226\n\021last_" +
      "updated_date\030\002 \001(\0132\033.google.protobuf.Int" +
      "64ValueB \n\034im.turms.turms.pojo.responseP" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          im.turms.turms.pojo.dto.UserInfoOuterClass.getDescriptor(),
        });
    internal_static_im_turms_proto_UsersInfosWithVersion_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_im_turms_proto_UsersInfosWithVersion_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_turms_proto_UsersInfosWithVersion_descriptor,
        new java.lang.String[] { "UserInfos", "LastUpdatedDate", });
    com.google.protobuf.WrappersProto.getDescriptor();
    im.turms.turms.pojo.dto.UserInfoOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
