// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dto/signal/acknowledge.proto

package im.turms.turms.pojo.dto;

public final class AcknowledgeOuterClass {
  private AcknowledgeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_turms_proto_Acknowledge_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_turms_proto_Acknowledge_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034dto/signal/acknowledge.proto\022\016im.turms" +
      ".proto\032\036google/protobuf/wrappers.proto\"U" +
      "\n\013Acknowledge\022\025\n\rdelivery_date\030\001 \001(\003\022/\n\n" +
      "message_id\030\002 \001(\0132\033.google.protobuf.Int64" +
      "ValueB\033\n\027im.turms.turms.pojo.dtoP\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_im_turms_proto_Acknowledge_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_im_turms_proto_Acknowledge_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_turms_proto_Acknowledge_descriptor,
        new java.lang.String[] { "DeliveryDate", "MessageId", });
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
