// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dto/group/group_join_request.proto

package im.turms.turms.pojo.dto;

public final class GroupJoinRequestOuterClass {
  private GroupJoinRequestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_turms_proto_GroupJoinRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_turms_proto_GroupJoinRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"dto/group/group_join_request.proto\022\016im" +
      ".turms.proto\032\036google/protobuf/wrappers.p" +
      "roto\032\035constant/request_status.proto\"\230\003\n\020" +
      "GroupJoinRequest\022\'\n\002id\030\001 \001(\0132\033.google.pr" +
      "otobuf.Int64Value\0222\n\rcreation_date\030\002 \001(\013" +
      "2\033.google.protobuf.Int64Value\022-\n\007content" +
      "\030\003 \001(\0132\034.google.protobuf.StringValue\022-\n\006" +
      "status\030\004 \001(\0162\035.im.turms.proto.RequestSta" +
      "tus\0224\n\017expiration_date\030\005 \001(\0132\033.google.pr" +
      "otobuf.Int64Value\022-\n\010group_id\030\006 \001(\0132\033.go" +
      "ogle.protobuf.Int64Value\0221\n\014requester_id" +
      "\030\007 \001(\0132\033.google.protobuf.Int64Value\0221\n\014r" +
      "esponder_id\030\010 \001(\0132\033.google.protobuf.Int6" +
      "4ValueB\033\n\027im.turms.turms.pojo.dtoP\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          im.turms.turms.constant.RequestStatusOuterClass.getDescriptor(),
        });
    internal_static_im_turms_proto_GroupJoinRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_im_turms_proto_GroupJoinRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_turms_proto_GroupJoinRequest_descriptor,
        new java.lang.String[] { "Id", "CreationDate", "Content", "Status", "ExpirationDate", "GroupId", "RequesterId", "ResponderId", });
    com.google.protobuf.WrappersProto.getDescriptor();
    im.turms.turms.constant.RequestStatusOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
