// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dto/message/message.proto

package im.turms.turms.pojo.dto;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:im.turms.proto.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Int64Value id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>.google.protobuf.Int64Value id = 1;</code>
   * @return The id.
   */
  com.google.protobuf.Int64Value getId();
  /**
   * <code>.google.protobuf.Int64Value id = 1;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getIdOrBuilder();

  /**
   * <code>.im.turms.proto.ChatType chat_type = 2;</code>
   * @return The enum numeric value on the wire for chatType.
   */
  int getChatTypeValue();
  /**
   * <code>.im.turms.proto.ChatType chat_type = 2;</code>
   * @return The chatType.
   */
  im.turms.turms.constant.ChatType getChatType();

  /**
   * <code>.google.protobuf.Int64Value delivery_date = 3;</code>
   * @return Whether the deliveryDate field is set.
   */
  boolean hasDeliveryDate();
  /**
   * <code>.google.protobuf.Int64Value delivery_date = 3;</code>
   * @return The deliveryDate.
   */
  com.google.protobuf.Int64Value getDeliveryDate();
  /**
   * <code>.google.protobuf.Int64Value delivery_date = 3;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getDeliveryDateOrBuilder();

  /**
   * <code>.google.protobuf.Int64Value deletion_date = 4;</code>
   * @return Whether the deletionDate field is set.
   */
  boolean hasDeletionDate();
  /**
   * <code>.google.protobuf.Int64Value deletion_date = 4;</code>
   * @return The deletionDate.
   */
  com.google.protobuf.Int64Value getDeletionDate();
  /**
   * <code>.google.protobuf.Int64Value deletion_date = 4;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getDeletionDateOrBuilder();

  /**
   * <code>.google.protobuf.StringValue text = 5;</code>
   * @return Whether the text field is set.
   */
  boolean hasText();
  /**
   * <code>.google.protobuf.StringValue text = 5;</code>
   * @return The text.
   */
  com.google.protobuf.StringValue getText();
  /**
   * <code>.google.protobuf.StringValue text = 5;</code>
   */
  com.google.protobuf.StringValueOrBuilder getTextOrBuilder();

  /**
   * <code>.google.protobuf.Int64Value from_id = 6;</code>
   * @return Whether the fromId field is set.
   */
  boolean hasFromId();
  /**
   * <code>.google.protobuf.Int64Value from_id = 6;</code>
   * @return The fromId.
   */
  com.google.protobuf.Int64Value getFromId();
  /**
   * <code>.google.protobuf.Int64Value from_id = 6;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getFromIdOrBuilder();

  /**
   * <code>.google.protobuf.Int64Value to_id = 7;</code>
   * @return Whether the toId field is set.
   */
  boolean hasToId();
  /**
   * <code>.google.protobuf.Int64Value to_id = 7;</code>
   * @return The toId.
   */
  com.google.protobuf.Int64Value getToId();
  /**
   * <code>.google.protobuf.Int64Value to_id = 7;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getToIdOrBuilder();

  /**
   * <code>repeated .google.protobuf.BytesValue records = 8;</code>
   */
  java.util.List<com.google.protobuf.BytesValue> 
      getRecordsList();
  /**
   * <code>repeated .google.protobuf.BytesValue records = 8;</code>
   */
  com.google.protobuf.BytesValue getRecords(int index);
  /**
   * <code>repeated .google.protobuf.BytesValue records = 8;</code>
   */
  int getRecordsCount();
  /**
   * <code>repeated .google.protobuf.BytesValue records = 8;</code>
   */
  java.util.List<? extends com.google.protobuf.BytesValueOrBuilder> 
      getRecordsOrBuilderList();
  /**
   * <code>repeated .google.protobuf.BytesValue records = 8;</code>
   */
  com.google.protobuf.BytesValueOrBuilder getRecordsOrBuilder(
      int index);
}
