// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dto/message/message.proto

package im.turms.turms.pojo.dto;

/**
 * Protobuf type {@code im.turms.proto.Message}
 */
public  final class Message extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:im.turms.proto.Message)
    MessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Message.newBuilder() to construct.
  private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Message() {
    chatType_ = 0;
    records_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Message();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Message(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.Int64Value.Builder subBuilder = null;
            if (id_ != null) {
              subBuilder = id_.toBuilder();
            }
            id_ = input.readMessage(com.google.protobuf.Int64Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(id_);
              id_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            chatType_ = rawValue;
            break;
          }
          case 26: {
            com.google.protobuf.Int64Value.Builder subBuilder = null;
            if (deliveryDate_ != null) {
              subBuilder = deliveryDate_.toBuilder();
            }
            deliveryDate_ = input.readMessage(com.google.protobuf.Int64Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(deliveryDate_);
              deliveryDate_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.google.protobuf.Int64Value.Builder subBuilder = null;
            if (deletionDate_ != null) {
              subBuilder = deletionDate_.toBuilder();
            }
            deletionDate_ = input.readMessage(com.google.protobuf.Int64Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(deletionDate_);
              deletionDate_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (text_ != null) {
              subBuilder = text_.toBuilder();
            }
            text_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(text_);
              text_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            com.google.protobuf.Int64Value.Builder subBuilder = null;
            if (fromId_ != null) {
              subBuilder = fromId_.toBuilder();
            }
            fromId_ = input.readMessage(com.google.protobuf.Int64Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(fromId_);
              fromId_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            com.google.protobuf.Int64Value.Builder subBuilder = null;
            if (toId_ != null) {
              subBuilder = toId_.toBuilder();
            }
            toId_ = input.readMessage(com.google.protobuf.Int64Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(toId_);
              toId_ = subBuilder.buildPartial();
            }

            break;
          }
          case 66: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              records_ = new java.util.ArrayList<com.google.protobuf.BytesValue>();
              mutable_bitField0_ |= 0x00000001;
            }
            records_.add(
                input.readMessage(com.google.protobuf.BytesValue.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        records_ = java.util.Collections.unmodifiableList(records_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return im.turms.turms.pojo.dto.MessageOuterClass.internal_static_im_turms_proto_Message_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return im.turms.turms.pojo.dto.MessageOuterClass.internal_static_im_turms_proto_Message_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            im.turms.turms.pojo.dto.Message.class, im.turms.turms.pojo.dto.Message.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private com.google.protobuf.Int64Value id_;
  /**
   * <code>.google.protobuf.Int64Value id = 1;</code>
   * @return Whether the id field is set.
   */
  public boolean hasId() {
    return id_ != null;
  }
  /**
   * <code>.google.protobuf.Int64Value id = 1;</code>
   * @return The id.
   */
  public com.google.protobuf.Int64Value getId() {
    return id_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : id_;
  }
  /**
   * <code>.google.protobuf.Int64Value id = 1;</code>
   */
  public com.google.protobuf.Int64ValueOrBuilder getIdOrBuilder() {
    return getId();
  }

  public static final int CHAT_TYPE_FIELD_NUMBER = 2;
  private int chatType_;
  /**
   * <code>.im.turms.proto.ChatType chat_type = 2;</code>
   * @return The enum numeric value on the wire for chatType.
   */
  public int getChatTypeValue() {
    return chatType_;
  }
  /**
   * <code>.im.turms.proto.ChatType chat_type = 2;</code>
   * @return The chatType.
   */
  public im.turms.turms.constant.ChatType getChatType() {
    @SuppressWarnings("deprecation")
    im.turms.turms.constant.ChatType result = im.turms.turms.constant.ChatType.valueOf(chatType_);
    return result == null ? im.turms.turms.constant.ChatType.UNRECOGNIZED : result;
  }

  public static final int DELIVERY_DATE_FIELD_NUMBER = 3;
  private com.google.protobuf.Int64Value deliveryDate_;
  /**
   * <code>.google.protobuf.Int64Value delivery_date = 3;</code>
   * @return Whether the deliveryDate field is set.
   */
  public boolean hasDeliveryDate() {
    return deliveryDate_ != null;
  }
  /**
   * <code>.google.protobuf.Int64Value delivery_date = 3;</code>
   * @return The deliveryDate.
   */
  public com.google.protobuf.Int64Value getDeliveryDate() {
    return deliveryDate_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : deliveryDate_;
  }
  /**
   * <code>.google.protobuf.Int64Value delivery_date = 3;</code>
   */
  public com.google.protobuf.Int64ValueOrBuilder getDeliveryDateOrBuilder() {
    return getDeliveryDate();
  }

  public static final int DELETION_DATE_FIELD_NUMBER = 4;
  private com.google.protobuf.Int64Value deletionDate_;
  /**
   * <code>.google.protobuf.Int64Value deletion_date = 4;</code>
   * @return Whether the deletionDate field is set.
   */
  public boolean hasDeletionDate() {
    return deletionDate_ != null;
  }
  /**
   * <code>.google.protobuf.Int64Value deletion_date = 4;</code>
   * @return The deletionDate.
   */
  public com.google.protobuf.Int64Value getDeletionDate() {
    return deletionDate_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : deletionDate_;
  }
  /**
   * <code>.google.protobuf.Int64Value deletion_date = 4;</code>
   */
  public com.google.protobuf.Int64ValueOrBuilder getDeletionDateOrBuilder() {
    return getDeletionDate();
  }

  public static final int TEXT_FIELD_NUMBER = 5;
  private com.google.protobuf.StringValue text_;
  /**
   * <code>.google.protobuf.StringValue text = 5;</code>
   * @return Whether the text field is set.
   */
  public boolean hasText() {
    return text_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue text = 5;</code>
   * @return The text.
   */
  public com.google.protobuf.StringValue getText() {
    return text_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : text_;
  }
  /**
   * <code>.google.protobuf.StringValue text = 5;</code>
   */
  public com.google.protobuf.StringValueOrBuilder getTextOrBuilder() {
    return getText();
  }

  public static final int FROM_ID_FIELD_NUMBER = 6;
  private com.google.protobuf.Int64Value fromId_;
  /**
   * <code>.google.protobuf.Int64Value from_id = 6;</code>
   * @return Whether the fromId field is set.
   */
  public boolean hasFromId() {
    return fromId_ != null;
  }
  /**
   * <code>.google.protobuf.Int64Value from_id = 6;</code>
   * @return The fromId.
   */
  public com.google.protobuf.Int64Value getFromId() {
    return fromId_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : fromId_;
  }
  /**
   * <code>.google.protobuf.Int64Value from_id = 6;</code>
   */
  public com.google.protobuf.Int64ValueOrBuilder getFromIdOrBuilder() {
    return getFromId();
  }

  public static final int TO_ID_FIELD_NUMBER = 7;
  private com.google.protobuf.Int64Value toId_;
  /**
   * <code>.google.protobuf.Int64Value to_id = 7;</code>
   * @return Whether the toId field is set.
   */
  public boolean hasToId() {
    return toId_ != null;
  }
  /**
   * <code>.google.protobuf.Int64Value to_id = 7;</code>
   * @return The toId.
   */
  public com.google.protobuf.Int64Value getToId() {
    return toId_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : toId_;
  }
  /**
   * <code>.google.protobuf.Int64Value to_id = 7;</code>
   */
  public com.google.protobuf.Int64ValueOrBuilder getToIdOrBuilder() {
    return getToId();
  }

  public static final int RECORDS_FIELD_NUMBER = 8;
  private java.util.List<com.google.protobuf.BytesValue> records_;
  /**
   * <code>repeated .google.protobuf.BytesValue records = 8;</code>
   */
  public java.util.List<com.google.protobuf.BytesValue> getRecordsList() {
    return records_;
  }
  /**
   * <code>repeated .google.protobuf.BytesValue records = 8;</code>
   */
  public java.util.List<? extends com.google.protobuf.BytesValueOrBuilder>
      getRecordsOrBuilderList() {
    return records_;
  }
  /**
   * <code>repeated .google.protobuf.BytesValue records = 8;</code>
   */
  public int getRecordsCount() {
    return records_.size();
  }
  /**
   * <code>repeated .google.protobuf.BytesValue records = 8;</code>
   */
  public com.google.protobuf.BytesValue getRecords(int index) {
    return records_.get(index);
  }
  /**
   * <code>repeated .google.protobuf.BytesValue records = 8;</code>
   */
  public com.google.protobuf.BytesValueOrBuilder getRecordsOrBuilder(
      int index) {
    return records_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != null) {
      output.writeMessage(1, getId());
    }
    if (chatType_ != im.turms.turms.constant.ChatType.PRIVATE.getNumber()) {
      output.writeEnum(2, chatType_);
    }
    if (deliveryDate_ != null) {
      output.writeMessage(3, getDeliveryDate());
    }
    if (deletionDate_ != null) {
      output.writeMessage(4, getDeletionDate());
    }
    if (text_ != null) {
      output.writeMessage(5, getText());
    }
    if (fromId_ != null) {
      output.writeMessage(6, getFromId());
    }
    if (toId_ != null) {
      output.writeMessage(7, getToId());
    }
    for (int i = 0; i < records_.size(); i++) {
      output.writeMessage(8, records_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getId());
    }
    if (chatType_ != im.turms.turms.constant.ChatType.PRIVATE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, chatType_);
    }
    if (deliveryDate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getDeliveryDate());
    }
    if (deletionDate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getDeletionDate());
    }
    if (text_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getText());
    }
    if (fromId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getFromId());
    }
    if (toId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getToId());
    }
    for (int i = 0; i < records_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, records_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof im.turms.turms.pojo.dto.Message)) {
      return super.equals(obj);
    }
    im.turms.turms.pojo.dto.Message other = (im.turms.turms.pojo.dto.Message) obj;

    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (!getId()
          .equals(other.getId())) return false;
    }
    if (chatType_ != other.chatType_) return false;
    if (hasDeliveryDate() != other.hasDeliveryDate()) return false;
    if (hasDeliveryDate()) {
      if (!getDeliveryDate()
          .equals(other.getDeliveryDate())) return false;
    }
    if (hasDeletionDate() != other.hasDeletionDate()) return false;
    if (hasDeletionDate()) {
      if (!getDeletionDate()
          .equals(other.getDeletionDate())) return false;
    }
    if (hasText() != other.hasText()) return false;
    if (hasText()) {
      if (!getText()
          .equals(other.getText())) return false;
    }
    if (hasFromId() != other.hasFromId()) return false;
    if (hasFromId()) {
      if (!getFromId()
          .equals(other.getFromId())) return false;
    }
    if (hasToId() != other.hasToId()) return false;
    if (hasToId()) {
      if (!getToId()
          .equals(other.getToId())) return false;
    }
    if (!getRecordsList()
        .equals(other.getRecordsList())) return false;
    return unknownFields.equals(other.unknownFields);
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
    }
    hash = (37 * hash) + CHAT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + chatType_;
    if (hasDeliveryDate()) {
      hash = (37 * hash) + DELIVERY_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDeliveryDate().hashCode();
    }
    if (hasDeletionDate()) {
      hash = (37 * hash) + DELETION_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDeletionDate().hashCode();
    }
    if (hasText()) {
      hash = (37 * hash) + TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getText().hashCode();
    }
    if (hasFromId()) {
      hash = (37 * hash) + FROM_ID_FIELD_NUMBER;
      hash = (53 * hash) + getFromId().hashCode();
    }
    if (hasToId()) {
      hash = (37 * hash) + TO_ID_FIELD_NUMBER;
      hash = (53 * hash) + getToId().hashCode();
    }
    if (getRecordsCount() > 0) {
      hash = (37 * hash) + RECORDS_FIELD_NUMBER;
      hash = (53 * hash) + getRecordsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static im.turms.turms.pojo.dto.Message parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static im.turms.turms.pojo.dto.Message parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static im.turms.turms.pojo.dto.Message parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static im.turms.turms.pojo.dto.Message parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static im.turms.turms.pojo.dto.Message parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static im.turms.turms.pojo.dto.Message parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static im.turms.turms.pojo.dto.Message parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static im.turms.turms.pojo.dto.Message parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static im.turms.turms.pojo.dto.Message parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static im.turms.turms.pojo.dto.Message parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static im.turms.turms.pojo.dto.Message parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static im.turms.turms.pojo.dto.Message parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(im.turms.turms.pojo.dto.Message prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code im.turms.proto.Message}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:im.turms.proto.Message)
      im.turms.turms.pojo.dto.MessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return im.turms.turms.pojo.dto.MessageOuterClass.internal_static_im_turms_proto_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return im.turms.turms.pojo.dto.MessageOuterClass.internal_static_im_turms_proto_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              im.turms.turms.pojo.dto.Message.class, im.turms.turms.pojo.dto.Message.Builder.class);
    }

    // Construct using im.turms.turms.pojo.dto.Message.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRecordsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (idBuilder_ == null) {
        id_ = null;
      } else {
        id_ = null;
        idBuilder_ = null;
      }
      chatType_ = 0;

      if (deliveryDateBuilder_ == null) {
        deliveryDate_ = null;
      } else {
        deliveryDate_ = null;
        deliveryDateBuilder_ = null;
      }
      if (deletionDateBuilder_ == null) {
        deletionDate_ = null;
      } else {
        deletionDate_ = null;
        deletionDateBuilder_ = null;
      }
      if (textBuilder_ == null) {
        text_ = null;
      } else {
        text_ = null;
        textBuilder_ = null;
      }
      if (fromIdBuilder_ == null) {
        fromId_ = null;
      } else {
        fromId_ = null;
        fromIdBuilder_ = null;
      }
      if (toIdBuilder_ == null) {
        toId_ = null;
      } else {
        toId_ = null;
        toIdBuilder_ = null;
      }
      if (recordsBuilder_ == null) {
        records_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        recordsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return im.turms.turms.pojo.dto.MessageOuterClass.internal_static_im_turms_proto_Message_descriptor;
    }

    @java.lang.Override
    public im.turms.turms.pojo.dto.Message getDefaultInstanceForType() {
      return im.turms.turms.pojo.dto.Message.getDefaultInstance();
    }

    @java.lang.Override
    public im.turms.turms.pojo.dto.Message build() {
      im.turms.turms.pojo.dto.Message result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public im.turms.turms.pojo.dto.Message buildPartial() {
      im.turms.turms.pojo.dto.Message result = new im.turms.turms.pojo.dto.Message(this);
      int from_bitField0_ = bitField0_;
      if (idBuilder_ == null) {
        result.id_ = id_;
      } else {
        result.id_ = idBuilder_.build();
      }
      result.chatType_ = chatType_;
      if (deliveryDateBuilder_ == null) {
        result.deliveryDate_ = deliveryDate_;
      } else {
        result.deliveryDate_ = deliveryDateBuilder_.build();
      }
      if (deletionDateBuilder_ == null) {
        result.deletionDate_ = deletionDate_;
      } else {
        result.deletionDate_ = deletionDateBuilder_.build();
      }
      if (textBuilder_ == null) {
        result.text_ = text_;
      } else {
        result.text_ = textBuilder_.build();
      }
      if (fromIdBuilder_ == null) {
        result.fromId_ = fromId_;
      } else {
        result.fromId_ = fromIdBuilder_.build();
      }
      if (toIdBuilder_ == null) {
        result.toId_ = toId_;
      } else {
        result.toId_ = toIdBuilder_.build();
      }
      if (recordsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          records_ = java.util.Collections.unmodifiableList(records_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.records_ = records_;
      } else {
        result.records_ = recordsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof im.turms.turms.pojo.dto.Message) {
        return mergeFrom((im.turms.turms.pojo.dto.Message)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(im.turms.turms.pojo.dto.Message other) {
      if (other == im.turms.turms.pojo.dto.Message.getDefaultInstance()) return this;
      if (other.hasId()) {
        mergeId(other.getId());
      }
      if (other.chatType_ != 0) {
        setChatTypeValue(other.getChatTypeValue());
      }
      if (other.hasDeliveryDate()) {
        mergeDeliveryDate(other.getDeliveryDate());
      }
      if (other.hasDeletionDate()) {
        mergeDeletionDate(other.getDeletionDate());
      }
      if (other.hasText()) {
        mergeText(other.getText());
      }
      if (other.hasFromId()) {
        mergeFromId(other.getFromId());
      }
      if (other.hasToId()) {
        mergeToId(other.getToId());
      }
      if (recordsBuilder_ == null) {
        if (!other.records_.isEmpty()) {
          if (records_.isEmpty()) {
            records_ = other.records_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRecordsIsMutable();
            records_.addAll(other.records_);
          }
          onChanged();
        }
      } else {
        if (!other.records_.isEmpty()) {
          if (recordsBuilder_.isEmpty()) {
            recordsBuilder_.dispose();
            recordsBuilder_ = null;
            records_ = other.records_;
            bitField0_ = (bitField0_ & ~0x00000001);
            recordsBuilder_ =
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRecordsFieldBuilder() : null;
          } else {
            recordsBuilder_.addAllMessages(other.records_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      im.turms.turms.pojo.dto.Message parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (im.turms.turms.pojo.dto.Message) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Int64Value id_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> idBuilder_;
    /**
     * <code>.google.protobuf.Int64Value id = 1;</code>
     * @return Whether the id field is set.
     */
    public boolean hasId() {
      return idBuilder_ != null || id_ != null;
    }
    /**
     * <code>.google.protobuf.Int64Value id = 1;</code>
     * @return The id.
     */
    public com.google.protobuf.Int64Value getId() {
      if (idBuilder_ == null) {
        return id_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : id_;
      } else {
        return idBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int64Value id = 1;</code>
     */
    public Builder setId(com.google.protobuf.Int64Value value) {
      if (idBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        id_ = value;
        onChanged();
      } else {
        idBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value id = 1;</code>
     */
    public Builder setId(
        com.google.protobuf.Int64Value.Builder builderForValue) {
      if (idBuilder_ == null) {
        id_ = builderForValue.build();
        onChanged();
      } else {
        idBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value id = 1;</code>
     */
    public Builder mergeId(com.google.protobuf.Int64Value value) {
      if (idBuilder_ == null) {
        if (id_ != null) {
          id_ =
            com.google.protobuf.Int64Value.newBuilder(id_).mergeFrom(value).buildPartial();
        } else {
          id_ = value;
        }
        onChanged();
      } else {
        idBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value id = 1;</code>
     */
    public Builder clearId() {
      if (idBuilder_ == null) {
        id_ = null;
        onChanged();
      } else {
        id_ = null;
        idBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value id = 1;</code>
     */
    public com.google.protobuf.Int64Value.Builder getIdBuilder() {

      onChanged();
      return getIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int64Value id = 1;</code>
     */
    public com.google.protobuf.Int64ValueOrBuilder getIdOrBuilder() {
      if (idBuilder_ != null) {
        return idBuilder_.getMessageOrBuilder();
      } else {
        return id_ == null ?
            com.google.protobuf.Int64Value.getDefaultInstance() : id_;
      }
    }
    /**
     * <code>.google.protobuf.Int64Value id = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>
        getIdFieldBuilder() {
      if (idBuilder_ == null) {
        idBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                getId(),
                getParentForChildren(),
                isClean());
        id_ = null;
      }
      return idBuilder_;
    }

    private int chatType_ = 0;
    /**
     * <code>.im.turms.proto.ChatType chat_type = 2;</code>
     * @return The enum numeric value on the wire for chatType.
     */
    public int getChatTypeValue() {
      return chatType_;
    }
    /**
     * <code>.im.turms.proto.ChatType chat_type = 2;</code>
     * @param value The enum numeric value on the wire for chatType to set.
     * @return This builder for chaining.
     */
    public Builder setChatTypeValue(int value) {
      chatType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.im.turms.proto.ChatType chat_type = 2;</code>
     * @return The chatType.
     */
    public im.turms.turms.constant.ChatType getChatType() {
      @SuppressWarnings("deprecation")
      im.turms.turms.constant.ChatType result = im.turms.turms.constant.ChatType.valueOf(chatType_);
      return result == null ? im.turms.turms.constant.ChatType.UNRECOGNIZED : result;
    }
    /**
     * <code>.im.turms.proto.ChatType chat_type = 2;</code>
     * @param value The chatType to set.
     * @return This builder for chaining.
     */
    public Builder setChatType(im.turms.turms.constant.ChatType value) {
      if (value == null) {
        throw new NullPointerException();
      }

      chatType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.im.turms.proto.ChatType chat_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearChatType() {

      chatType_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Int64Value deliveryDate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> deliveryDateBuilder_;
    /**
     * <code>.google.protobuf.Int64Value delivery_date = 3;</code>
     * @return Whether the deliveryDate field is set.
     */
    public boolean hasDeliveryDate() {
      return deliveryDateBuilder_ != null || deliveryDate_ != null;
    }
    /**
     * <code>.google.protobuf.Int64Value delivery_date = 3;</code>
     * @return The deliveryDate.
     */
    public com.google.protobuf.Int64Value getDeliveryDate() {
      if (deliveryDateBuilder_ == null) {
        return deliveryDate_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : deliveryDate_;
      } else {
        return deliveryDateBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int64Value delivery_date = 3;</code>
     */
    public Builder setDeliveryDate(com.google.protobuf.Int64Value value) {
      if (deliveryDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        deliveryDate_ = value;
        onChanged();
      } else {
        deliveryDateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value delivery_date = 3;</code>
     */
    public Builder setDeliveryDate(
        com.google.protobuf.Int64Value.Builder builderForValue) {
      if (deliveryDateBuilder_ == null) {
        deliveryDate_ = builderForValue.build();
        onChanged();
      } else {
        deliveryDateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value delivery_date = 3;</code>
     */
    public Builder mergeDeliveryDate(com.google.protobuf.Int64Value value) {
      if (deliveryDateBuilder_ == null) {
        if (deliveryDate_ != null) {
          deliveryDate_ =
            com.google.protobuf.Int64Value.newBuilder(deliveryDate_).mergeFrom(value).buildPartial();
        } else {
          deliveryDate_ = value;
        }
        onChanged();
      } else {
        deliveryDateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value delivery_date = 3;</code>
     */
    public Builder clearDeliveryDate() {
      if (deliveryDateBuilder_ == null) {
        deliveryDate_ = null;
        onChanged();
      } else {
        deliveryDate_ = null;
        deliveryDateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value delivery_date = 3;</code>
     */
    public com.google.protobuf.Int64Value.Builder getDeliveryDateBuilder() {

      onChanged();
      return getDeliveryDateFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int64Value delivery_date = 3;</code>
     */
    public com.google.protobuf.Int64ValueOrBuilder getDeliveryDateOrBuilder() {
      if (deliveryDateBuilder_ != null) {
        return deliveryDateBuilder_.getMessageOrBuilder();
      } else {
        return deliveryDate_ == null ?
            com.google.protobuf.Int64Value.getDefaultInstance() : deliveryDate_;
      }
    }
    /**
     * <code>.google.protobuf.Int64Value delivery_date = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>
        getDeliveryDateFieldBuilder() {
      if (deliveryDateBuilder_ == null) {
        deliveryDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                getDeliveryDate(),
                getParentForChildren(),
                isClean());
        deliveryDate_ = null;
      }
      return deliveryDateBuilder_;
    }

    private com.google.protobuf.Int64Value deletionDate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> deletionDateBuilder_;
    /**
     * <code>.google.protobuf.Int64Value deletion_date = 4;</code>
     * @return Whether the deletionDate field is set.
     */
    public boolean hasDeletionDate() {
      return deletionDateBuilder_ != null || deletionDate_ != null;
    }
    /**
     * <code>.google.protobuf.Int64Value deletion_date = 4;</code>
     * @return The deletionDate.
     */
    public com.google.protobuf.Int64Value getDeletionDate() {
      if (deletionDateBuilder_ == null) {
        return deletionDate_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : deletionDate_;
      } else {
        return deletionDateBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int64Value deletion_date = 4;</code>
     */
    public Builder setDeletionDate(com.google.protobuf.Int64Value value) {
      if (deletionDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        deletionDate_ = value;
        onChanged();
      } else {
        deletionDateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value deletion_date = 4;</code>
     */
    public Builder setDeletionDate(
        com.google.protobuf.Int64Value.Builder builderForValue) {
      if (deletionDateBuilder_ == null) {
        deletionDate_ = builderForValue.build();
        onChanged();
      } else {
        deletionDateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value deletion_date = 4;</code>
     */
    public Builder mergeDeletionDate(com.google.protobuf.Int64Value value) {
      if (deletionDateBuilder_ == null) {
        if (deletionDate_ != null) {
          deletionDate_ =
            com.google.protobuf.Int64Value.newBuilder(deletionDate_).mergeFrom(value).buildPartial();
        } else {
          deletionDate_ = value;
        }
        onChanged();
      } else {
        deletionDateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value deletion_date = 4;</code>
     */
    public Builder clearDeletionDate() {
      if (deletionDateBuilder_ == null) {
        deletionDate_ = null;
        onChanged();
      } else {
        deletionDate_ = null;
        deletionDateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value deletion_date = 4;</code>
     */
    public com.google.protobuf.Int64Value.Builder getDeletionDateBuilder() {

      onChanged();
      return getDeletionDateFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int64Value deletion_date = 4;</code>
     */
    public com.google.protobuf.Int64ValueOrBuilder getDeletionDateOrBuilder() {
      if (deletionDateBuilder_ != null) {
        return deletionDateBuilder_.getMessageOrBuilder();
      } else {
        return deletionDate_ == null ?
            com.google.protobuf.Int64Value.getDefaultInstance() : deletionDate_;
      }
    }
    /**
     * <code>.google.protobuf.Int64Value deletion_date = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>
        getDeletionDateFieldBuilder() {
      if (deletionDateBuilder_ == null) {
        deletionDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                getDeletionDate(),
                getParentForChildren(),
                isClean());
        deletionDate_ = null;
      }
      return deletionDateBuilder_;
    }

    private com.google.protobuf.StringValue text_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> textBuilder_;
    /**
     * <code>.google.protobuf.StringValue text = 5;</code>
     * @return Whether the text field is set.
     */
    public boolean hasText() {
      return textBuilder_ != null || text_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue text = 5;</code>
     * @return The text.
     */
    public com.google.protobuf.StringValue getText() {
      if (textBuilder_ == null) {
        return text_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : text_;
      } else {
        return textBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue text = 5;</code>
     */
    public Builder setText(com.google.protobuf.StringValue value) {
      if (textBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        text_ = value;
        onChanged();
      } else {
        textBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue text = 5;</code>
     */
    public Builder setText(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (textBuilder_ == null) {
        text_ = builderForValue.build();
        onChanged();
      } else {
        textBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue text = 5;</code>
     */
    public Builder mergeText(com.google.protobuf.StringValue value) {
      if (textBuilder_ == null) {
        if (text_ != null) {
          text_ =
            com.google.protobuf.StringValue.newBuilder(text_).mergeFrom(value).buildPartial();
        } else {
          text_ = value;
        }
        onChanged();
      } else {
        textBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue text = 5;</code>
     */
    public Builder clearText() {
      if (textBuilder_ == null) {
        text_ = null;
        onChanged();
      } else {
        text_ = null;
        textBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue text = 5;</code>
     */
    public com.google.protobuf.StringValue.Builder getTextBuilder() {

      onChanged();
      return getTextFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue text = 5;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getTextOrBuilder() {
      if (textBuilder_ != null) {
        return textBuilder_.getMessageOrBuilder();
      } else {
        return text_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : text_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue text = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>
        getTextFieldBuilder() {
      if (textBuilder_ == null) {
        textBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getText(),
                getParentForChildren(),
                isClean());
        text_ = null;
      }
      return textBuilder_;
    }

    private com.google.protobuf.Int64Value fromId_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> fromIdBuilder_;
    /**
     * <code>.google.protobuf.Int64Value from_id = 6;</code>
     * @return Whether the fromId field is set.
     */
    public boolean hasFromId() {
      return fromIdBuilder_ != null || fromId_ != null;
    }
    /**
     * <code>.google.protobuf.Int64Value from_id = 6;</code>
     * @return The fromId.
     */
    public com.google.protobuf.Int64Value getFromId() {
      if (fromIdBuilder_ == null) {
        return fromId_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : fromId_;
      } else {
        return fromIdBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int64Value from_id = 6;</code>
     */
    public Builder setFromId(com.google.protobuf.Int64Value value) {
      if (fromIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        fromId_ = value;
        onChanged();
      } else {
        fromIdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value from_id = 6;</code>
     */
    public Builder setFromId(
        com.google.protobuf.Int64Value.Builder builderForValue) {
      if (fromIdBuilder_ == null) {
        fromId_ = builderForValue.build();
        onChanged();
      } else {
        fromIdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value from_id = 6;</code>
     */
    public Builder mergeFromId(com.google.protobuf.Int64Value value) {
      if (fromIdBuilder_ == null) {
        if (fromId_ != null) {
          fromId_ =
            com.google.protobuf.Int64Value.newBuilder(fromId_).mergeFrom(value).buildPartial();
        } else {
          fromId_ = value;
        }
        onChanged();
      } else {
        fromIdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value from_id = 6;</code>
     */
    public Builder clearFromId() {
      if (fromIdBuilder_ == null) {
        fromId_ = null;
        onChanged();
      } else {
        fromId_ = null;
        fromIdBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value from_id = 6;</code>
     */
    public com.google.protobuf.Int64Value.Builder getFromIdBuilder() {

      onChanged();
      return getFromIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int64Value from_id = 6;</code>
     */
    public com.google.protobuf.Int64ValueOrBuilder getFromIdOrBuilder() {
      if (fromIdBuilder_ != null) {
        return fromIdBuilder_.getMessageOrBuilder();
      } else {
        return fromId_ == null ?
            com.google.protobuf.Int64Value.getDefaultInstance() : fromId_;
      }
    }
    /**
     * <code>.google.protobuf.Int64Value from_id = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>
        getFromIdFieldBuilder() {
      if (fromIdBuilder_ == null) {
        fromIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                getFromId(),
                getParentForChildren(),
                isClean());
        fromId_ = null;
      }
      return fromIdBuilder_;
    }

    private com.google.protobuf.Int64Value toId_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> toIdBuilder_;
    /**
     * <code>.google.protobuf.Int64Value to_id = 7;</code>
     * @return Whether the toId field is set.
     */
    public boolean hasToId() {
      return toIdBuilder_ != null || toId_ != null;
    }
    /**
     * <code>.google.protobuf.Int64Value to_id = 7;</code>
     * @return The toId.
     */
    public com.google.protobuf.Int64Value getToId() {
      if (toIdBuilder_ == null) {
        return toId_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : toId_;
      } else {
        return toIdBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int64Value to_id = 7;</code>
     */
    public Builder setToId(com.google.protobuf.Int64Value value) {
      if (toIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        toId_ = value;
        onChanged();
      } else {
        toIdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value to_id = 7;</code>
     */
    public Builder setToId(
        com.google.protobuf.Int64Value.Builder builderForValue) {
      if (toIdBuilder_ == null) {
        toId_ = builderForValue.build();
        onChanged();
      } else {
        toIdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value to_id = 7;</code>
     */
    public Builder mergeToId(com.google.protobuf.Int64Value value) {
      if (toIdBuilder_ == null) {
        if (toId_ != null) {
          toId_ =
            com.google.protobuf.Int64Value.newBuilder(toId_).mergeFrom(value).buildPartial();
        } else {
          toId_ = value;
        }
        onChanged();
      } else {
        toIdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value to_id = 7;</code>
     */
    public Builder clearToId() {
      if (toIdBuilder_ == null) {
        toId_ = null;
        onChanged();
      } else {
        toId_ = null;
        toIdBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value to_id = 7;</code>
     */
    public com.google.protobuf.Int64Value.Builder getToIdBuilder() {

      onChanged();
      return getToIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int64Value to_id = 7;</code>
     */
    public com.google.protobuf.Int64ValueOrBuilder getToIdOrBuilder() {
      if (toIdBuilder_ != null) {
        return toIdBuilder_.getMessageOrBuilder();
      } else {
        return toId_ == null ?
            com.google.protobuf.Int64Value.getDefaultInstance() : toId_;
      }
    }
    /**
     * <code>.google.protobuf.Int64Value to_id = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>
        getToIdFieldBuilder() {
      if (toIdBuilder_ == null) {
        toIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                getToId(),
                getParentForChildren(),
                isClean());
        toId_ = null;
      }
      return toIdBuilder_;
    }

    private java.util.List<com.google.protobuf.BytesValue> records_ =
      java.util.Collections.emptyList();
    private void ensureRecordsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        records_ = new java.util.ArrayList<com.google.protobuf.BytesValue>(records_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.protobuf.BytesValue, com.google.protobuf.BytesValue.Builder, com.google.protobuf.BytesValueOrBuilder> recordsBuilder_;

    /**
     * <code>repeated .google.protobuf.BytesValue records = 8;</code>
     */
    public java.util.List<com.google.protobuf.BytesValue> getRecordsList() {
      if (recordsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(records_);
      } else {
        return recordsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .google.protobuf.BytesValue records = 8;</code>
     */
    public int getRecordsCount() {
      if (recordsBuilder_ == null) {
        return records_.size();
      } else {
        return recordsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .google.protobuf.BytesValue records = 8;</code>
     */
    public com.google.protobuf.BytesValue getRecords(int index) {
      if (recordsBuilder_ == null) {
        return records_.get(index);
      } else {
        return recordsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .google.protobuf.BytesValue records = 8;</code>
     */
    public Builder setRecords(
        int index, com.google.protobuf.BytesValue value) {
      if (recordsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecordsIsMutable();
        records_.set(index, value);
        onChanged();
      } else {
        recordsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.BytesValue records = 8;</code>
     */
    public Builder setRecords(
        int index, com.google.protobuf.BytesValue.Builder builderForValue) {
      if (recordsBuilder_ == null) {
        ensureRecordsIsMutable();
        records_.set(index, builderForValue.build());
        onChanged();
      } else {
        recordsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.BytesValue records = 8;</code>
     */
    public Builder addRecords(com.google.protobuf.BytesValue value) {
      if (recordsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecordsIsMutable();
        records_.add(value);
        onChanged();
      } else {
        recordsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.BytesValue records = 8;</code>
     */
    public Builder addRecords(
        int index, com.google.protobuf.BytesValue value) {
      if (recordsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecordsIsMutable();
        records_.add(index, value);
        onChanged();
      } else {
        recordsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.BytesValue records = 8;</code>
     */
    public Builder addRecords(
        com.google.protobuf.BytesValue.Builder builderForValue) {
      if (recordsBuilder_ == null) {
        ensureRecordsIsMutable();
        records_.add(builderForValue.build());
        onChanged();
      } else {
        recordsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.BytesValue records = 8;</code>
     */
    public Builder addRecords(
        int index, com.google.protobuf.BytesValue.Builder builderForValue) {
      if (recordsBuilder_ == null) {
        ensureRecordsIsMutable();
        records_.add(index, builderForValue.build());
        onChanged();
      } else {
        recordsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.BytesValue records = 8;</code>
     */
    public Builder addAllRecords(
        java.lang.Iterable<? extends com.google.protobuf.BytesValue> values) {
      if (recordsBuilder_ == null) {
        ensureRecordsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, records_);
        onChanged();
      } else {
        recordsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.BytesValue records = 8;</code>
     */
    public Builder clearRecords() {
      if (recordsBuilder_ == null) {
        records_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        recordsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.BytesValue records = 8;</code>
     */
    public Builder removeRecords(int index) {
      if (recordsBuilder_ == null) {
        ensureRecordsIsMutable();
        records_.remove(index);
        onChanged();
      } else {
        recordsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.BytesValue records = 8;</code>
     */
    public com.google.protobuf.BytesValue.Builder getRecordsBuilder(
        int index) {
      return getRecordsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .google.protobuf.BytesValue records = 8;</code>
     */
    public com.google.protobuf.BytesValueOrBuilder getRecordsOrBuilder(
        int index) {
      if (recordsBuilder_ == null) {
        return records_.get(index);  } else {
        return recordsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .google.protobuf.BytesValue records = 8;</code>
     */
    public java.util.List<? extends com.google.protobuf.BytesValueOrBuilder>
         getRecordsOrBuilderList() {
      if (recordsBuilder_ != null) {
        return recordsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(records_);
      }
    }
    /**
     * <code>repeated .google.protobuf.BytesValue records = 8;</code>
     */
    public com.google.protobuf.BytesValue.Builder addRecordsBuilder() {
      return getRecordsFieldBuilder().addBuilder(
          com.google.protobuf.BytesValue.getDefaultInstance());
    }
    /**
     * <code>repeated .google.protobuf.BytesValue records = 8;</code>
     */
    public com.google.protobuf.BytesValue.Builder addRecordsBuilder(
        int index) {
      return getRecordsFieldBuilder().addBuilder(
          index, com.google.protobuf.BytesValue.getDefaultInstance());
    }
    /**
     * <code>repeated .google.protobuf.BytesValue records = 8;</code>
     */
    public java.util.List<com.google.protobuf.BytesValue.Builder>
         getRecordsBuilderList() {
      return getRecordsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.protobuf.BytesValue, com.google.protobuf.BytesValue.Builder, com.google.protobuf.BytesValueOrBuilder>
        getRecordsFieldBuilder() {
      if (recordsBuilder_ == null) {
        recordsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.protobuf.BytesValue, com.google.protobuf.BytesValue.Builder, com.google.protobuf.BytesValueOrBuilder>(
                records_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        records_ = null;
      }
      return recordsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:im.turms.proto.Message)
  }

  // @@protoc_insertion_point(class_scope:im.turms.proto.Message)
  private static final im.turms.turms.pojo.dto.Message DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new im.turms.turms.pojo.dto.Message();
  }

  public static im.turms.turms.pojo.dto.Message getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Message>
      PARSER = new com.google.protobuf.AbstractParser<Message>() {
    @java.lang.Override
    public Message parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Message(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Message> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Message> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public im.turms.turms.pojo.dto.Message getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

