// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dto/message/messages_with_total.proto

package im.turms.turms.pojo.dto;

public final class MessagesWithTotalOuterClass {
  private MessagesWithTotalOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_turms_proto_MessagesWithTotal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_turms_proto_MessagesWithTotal_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%dto/message/messages_with_total.proto\022" +
      "\016im.turms.proto\032\030constant/chat_type.prot" +
      "o\032\031dto/message/message.proto\"\213\001\n\021Message" +
      "sWithTotal\022\r\n\005total\030\001 \001(\005\022+\n\tchat_type\030\002" +
      " \001(\0162\030.im.turms.proto.ChatType\022\017\n\007from_i" +
      "d\030\003 \001(\003\022)\n\010messages\030\004 \003(\0132\027.im.turms.pro" +
      "to.MessageB\033\n\027im.turms.turms.pojo.dtoP\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          im.turms.turms.constant.ChatTypeOuterClass.getDescriptor(),
          im.turms.turms.pojo.dto.MessageOuterClass.getDescriptor(),
        });
    internal_static_im_turms_proto_MessagesWithTotal_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_im_turms_proto_MessagesWithTotal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_turms_proto_MessagesWithTotal_descriptor,
        new java.lang.String[] { "Total", "ChatType", "FromId", "Messages", });
    im.turms.turms.constant.ChatTypeOuterClass.getDescriptor();
    im.turms.turms.pojo.dto.MessageOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
