// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dto/message/message_status.proto

package im.turms.turms.pojo.dto;

public final class MessageStatusOuterClass {
  private MessageStatusOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_turms_proto_MessageStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_turms_proto_MessageStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n dto/message/message_status.proto\022\016im.t" +
      "urms.proto\032\036google/protobuf/wrappers.pro" +
      "to\032&constant/message_delivery_status.pro" +
      "to\"\310\002\n\rMessageStatus\022/\n\nmessage_id\030\001 \001(\013" +
      "2\033.google.protobuf.Int64Value\022/\n\nto_user" +
      "_id\030\002 \001(\0132\033.google.protobuf.Int64Value\022>" +
      "\n\017delivery_status\030\003 \001(\0162%.im.turms.proto" +
      ".MessageDeliveryStatus\0223\n\016reception_date" +
      "\030\004 \001(\0132\033.google.protobuf.Int64Value\022.\n\tr" +
      "ead_date\030\005 \001(\0132\033.google.protobuf.Int64Va" +
      "lue\0220\n\013recall_date\030\006 \001(\0132\033.google.protob" +
      "uf.Int64ValueB\033\n\027im.turms.turms.pojo.dto" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          im.turms.turms.constant.MessageDeliveryStatusOuterClass.getDescriptor(),
        });
    internal_static_im_turms_proto_MessageStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_im_turms_proto_MessageStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_turms_proto_MessageStatus_descriptor,
        new java.lang.String[] { "MessageId", "ToUserId", "DeliveryStatus", "ReceptionDate", "ReadDate", "RecallDate", });
    com.google.protobuf.WrappersProto.getDescriptor();
    im.turms.turms.constant.MessageDeliveryStatusOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
