// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dto/user/user_location.proto

package im.turms.turms.pojo.dto;

public final class UserLocationOuterClass {
  private UserLocationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_turms_proto_UserLocation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_turms_proto_UserLocation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034dto/user/user_location.proto\022\016im.turms" +
      ".proto\032\036google/protobuf/wrappers.proto\"\276" +
      "\001\n\014UserLocation\022\020\n\010latitude\030\001 \001(\002\022\021\n\tlon" +
      "gitude\030\002 \001(\002\022*\n\004name\030\003 \001(\0132\034.google.prot" +
      "obuf.StringValue\022-\n\007address\030\004 \001(\0132\034.goog" +
      "le.protobuf.StringValue\022.\n\ttimestamp\030\005 \001" +
      "(\0132\033.google.protobuf.Int64ValueB\033\n\027im.tu" +
      "rms.turms.pojo.dtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_im_turms_proto_UserLocation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_im_turms_proto_UserLocation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_turms_proto_UserLocation_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", "Name", "Address", "Timestamp", });
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
