// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dto/user/user_info.proto

package im.turms.turms.pojo.dto;

public final class UserInfoOuterClass {
  private UserInfoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_turms_proto_UserInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_turms_proto_UserInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030dto/user/user_info.proto\022\016im.turms.pro" +
      "to\032\036google/protobuf/wrappers.proto\032&cons" +
      "tant/profile_access_strategy.proto\"\247\003\n\010U" +
      "serInfo\022\'\n\002id\030\001 \001(\0132\033.google.protobuf.In" +
      "t64Value\022*\n\004name\030\002 \001(\0132\034.google.protobuf" +
      ".StringValue\022+\n\005intro\030\003 \001(\0132\034.google.pro" +
      "tobuf.StringValue\0229\n\023profile_picture_url" +
      "\030\004 \001(\0132\034.google.protobuf.StringValue\0226\n\021" +
      "registration_date\030\005 \001(\0132\033.google.protobu" +
      "f.Int64Value\0222\n\rdeletion_date\030\006 \001(\0132\033.go" +
      "ogle.protobuf.Int64Value\022*\n\006active\030\007 \001(\013" +
      "2\032.google.protobuf.BoolValue\022F\n\027profile_" +
      "access_strategy\030\010 \001(\0162%.im.turms.proto.P" +
      "rofileAccessStrategyB\033\n\027im.turms.turms.p" +
      "ojo.dtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          im.turms.turms.constant.ProfileAccessStrategyOuterClass.getDescriptor(),
        });
    internal_static_im_turms_proto_UserInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_im_turms_proto_UserInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_turms_proto_UserInfo_descriptor,
        new java.lang.String[] { "Id", "Name", "Intro", "ProfilePictureUrl", "RegistrationDate", "DeletionDate", "Active", "ProfileAccessStrategy", });
    com.google.protobuf.WrappersProto.getDescriptor();
    im.turms.turms.constant.ProfileAccessStrategyOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
