// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dto/user/user_relationship_group.proto

package im.turms.turms.pojo.dto;

public interface UserRelationshipGroupOrBuilder extends
    // @@protoc_insertion_point(interface_extends:im.turms.proto.UserRelationshipGroup)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 index = 1;</code>
   * @return The index.
   */
  int getIndex();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
