// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dto/user/user_relationship_group.proto

package im.turms.turms.pojo.dto;

public final class UserRelationshipGroupOuterClass {
  private UserRelationshipGroupOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_turms_proto_UserRelationshipGroup_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_turms_proto_UserRelationshipGroup_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&dto/user/user_relationship_group.proto" +
      "\022\016im.turms.proto\"4\n\025UserRelationshipGrou" +
      "p\022\r\n\005index\030\001 \001(\005\022\014\n\004name\030\002 \001(\tB\033\n\027im.tur" +
      "ms.turms.pojo.dtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_im_turms_proto_UserRelationshipGroup_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_im_turms_proto_UserRelationshipGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_turms_proto_UserRelationshipGroup_descriptor,
        new java.lang.String[] { "Index", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
