// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: constant/chat_type.proto

package im.turms.turms.constant;

public final class ChatTypeOuterClass {
  private ChatTypeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030constant/chat_type.proto\022\016im.turms.pro" +
      "to*\"\n\010ChatType\022\013\n\007PRIVATE\020\000\022\t\n\005GROUP\020\001B\033" +
      "\n\027im.turms.turms.constantP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
