// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request/group/enrollment/check_group_join_question_answer_request.proto

package im.turms.turms.pojo.request;

public final class CheckGroupJoinQuestionAnswerRequestOuterClass {
  private CheckGroupJoinQuestionAnswerRequestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_turms_proto_CheckGroupJoinQuestionAnswerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_turms_proto_CheckGroupJoinQuestionAnswerRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nGrequest/group/enrollment/check_group_j" +
      "oin_question_answer_request.proto\022\016im.tu" +
      "rms.proto\"J\n#CheckGroupJoinQuestionAnswe" +
      "rRequest\022\023\n\013question_id\030\001 \001(\003\022\016\n\006answer\030" +
      "\002 \001(\tB\037\n\033im.turms.turms.pojo.requestP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_im_turms_proto_CheckGroupJoinQuestionAnswerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_im_turms_proto_CheckGroupJoinQuestionAnswerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_turms_proto_CheckGroupJoinQuestionAnswerRequest_descriptor,
        new java.lang.String[] { "QuestionId", "Answer", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
