// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request/group/enrollment/check_group_join_question_answer_request.proto

package im.turms.turms.pojo.request;

/**
 * Protobuf type {@code im.turms.proto.CheckGroupJoinQuestionAnswerRequest}
 */
public  final class CheckGroupJoinQuestionAnswerRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:im.turms.proto.CheckGroupJoinQuestionAnswerRequest)
    CheckGroupJoinQuestionAnswerRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CheckGroupJoinQuestionAnswerRequest.newBuilder() to construct.
  private CheckGroupJoinQuestionAnswerRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CheckGroupJoinQuestionAnswerRequest() {
    answer_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CheckGroupJoinQuestionAnswerRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CheckGroupJoinQuestionAnswerRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            questionId_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            answer_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequestOuterClass.internal_static_im_turms_proto_CheckGroupJoinQuestionAnswerRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequestOuterClass.internal_static_im_turms_proto_CheckGroupJoinQuestionAnswerRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequest.class, im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequest.Builder.class);
  }

  public static final int QUESTION_ID_FIELD_NUMBER = 1;
  private long questionId_;
  /**
   * <code>int64 question_id = 1;</code>
   * @return The questionId.
   */
  public long getQuestionId() {
    return questionId_;
  }

  public static final int ANSWER_FIELD_NUMBER = 2;
  private volatile java.lang.Object answer_;
  /**
   * <code>string answer = 2;</code>
   * @return The answer.
   */
  public java.lang.String getAnswer() {
    java.lang.Object ref = answer_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      answer_ = s;
      return s;
    }
  }
  /**
   * <code>string answer = 2;</code>
   * @return The bytes for answer.
   */
  public com.google.protobuf.ByteString
      getAnswerBytes() {
    java.lang.Object ref = answer_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      answer_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (questionId_ != 0L) {
      output.writeInt64(1, questionId_);
    }
    if (!getAnswerBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, answer_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (questionId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, questionId_);
    }
    if (!getAnswerBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, answer_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequest)) {
      return super.equals(obj);
    }
    im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequest other = (im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequest) obj;

    if (getQuestionId()
        != other.getQuestionId()) return false;
    if (!getAnswer()
        .equals(other.getAnswer())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + QUESTION_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getQuestionId());
    hash = (37 * hash) + ANSWER_FIELD_NUMBER;
    hash = (53 * hash) + getAnswer().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code im.turms.proto.CheckGroupJoinQuestionAnswerRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:im.turms.proto.CheckGroupJoinQuestionAnswerRequest)
      im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequestOuterClass.internal_static_im_turms_proto_CheckGroupJoinQuestionAnswerRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequestOuterClass.internal_static_im_turms_proto_CheckGroupJoinQuestionAnswerRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequest.class, im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequest.Builder.class);
    }

    // Construct using im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      questionId_ = 0L;

      answer_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequestOuterClass.internal_static_im_turms_proto_CheckGroupJoinQuestionAnswerRequest_descriptor;
    }

    @java.lang.Override
    public im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequest getDefaultInstanceForType() {
      return im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequest.getDefaultInstance();
    }

    @java.lang.Override
    public im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequest build() {
      im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequest buildPartial() {
      im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequest result = new im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequest(this);
      result.questionId_ = questionId_;
      result.answer_ = answer_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequest) {
        return mergeFrom((im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequest other) {
      if (other == im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequest.getDefaultInstance()) return this;
      if (other.getQuestionId() != 0L) {
        setQuestionId(other.getQuestionId());
      }
      if (!other.getAnswer().isEmpty()) {
        answer_ = other.answer_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long questionId_ ;
    /**
     * <code>int64 question_id = 1;</code>
     * @return The questionId.
     */
    public long getQuestionId() {
      return questionId_;
    }
    /**
     * <code>int64 question_id = 1;</code>
     * @param value The questionId to set.
     * @return This builder for chaining.
     */
    public Builder setQuestionId(long value) {
      
      questionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 question_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuestionId() {
      
      questionId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object answer_ = "";
    /**
     * <code>string answer = 2;</code>
     * @return The answer.
     */
    public java.lang.String getAnswer() {
      java.lang.Object ref = answer_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        answer_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string answer = 2;</code>
     * @return The bytes for answer.
     */
    public com.google.protobuf.ByteString
        getAnswerBytes() {
      java.lang.Object ref = answer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        answer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string answer = 2;</code>
     * @param value The answer to set.
     * @return This builder for chaining.
     */
    public Builder setAnswer(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      answer_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string answer = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAnswer() {
      
      answer_ = getDefaultInstance().getAnswer();
      onChanged();
      return this;
    }
    /**
     * <code>string answer = 2;</code>
     * @param value The bytes for answer to set.
     * @return This builder for chaining.
     */
    public Builder setAnswerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      answer_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:im.turms.proto.CheckGroupJoinQuestionAnswerRequest)
  }

  // @@protoc_insertion_point(class_scope:im.turms.proto.CheckGroupJoinQuestionAnswerRequest)
  private static final im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequest();
  }

  public static im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CheckGroupJoinQuestionAnswerRequest>
      PARSER = new com.google.protobuf.AbstractParser<CheckGroupJoinQuestionAnswerRequest>() {
    @java.lang.Override
    public CheckGroupJoinQuestionAnswerRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CheckGroupJoinQuestionAnswerRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CheckGroupJoinQuestionAnswerRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CheckGroupJoinQuestionAnswerRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

