// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request/group/member/create_group_member_request.proto

package im.turms.turms.pojo.request;

public interface CreateGroupMemberRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:im.turms.proto.CreateGroupMemberRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 group_id = 1;</code>
   * @return The groupId.
   */
  long getGroupId();

  /**
   * <code>int64 user_id = 2;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <code>.google.protobuf.Int64Value mute_end_date = 3;</code>
   * @return Whether the muteEndDate field is set.
   */
  boolean hasMuteEndDate();
  /**
   * <code>.google.protobuf.Int64Value mute_end_date = 3;</code>
   * @return The muteEndDate.
   */
  com.google.protobuf.Int64Value getMuteEndDate();
  /**
   * <code>.google.protobuf.Int64Value mute_end_date = 3;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getMuteEndDateOrBuilder();
}
