// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request/message/create_message_statuses_request.proto

package im.turms.turms.pojo.request;

/**
 * Protobuf type {@code im.turms.proto.CreateMessageStatusesRequest}
 */
public  final class CreateMessageStatusesRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:im.turms.proto.CreateMessageStatusesRequest)
    CreateMessageStatusesRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateMessageStatusesRequest.newBuilder() to construct.
  private CreateMessageStatusesRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateMessageStatusesRequest() {
    chatType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateMessageStatusesRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateMessageStatusesRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            messageId_ = input.readInt64();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            chatType_ = rawValue;
            break;
          }
          case 24: {

            toId_ = input.readInt64();
            break;
          }
          case 34: {
            com.google.protobuf.Int32Value.Builder subBuilder = null;
            if (burnAfter_ != null) {
              subBuilder = burnAfter_.toBuilder();
            }
            burnAfter_ = input.readMessage(com.google.protobuf.Int32Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(burnAfter_);
              burnAfter_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return im.turms.turms.pojo.request.CreateMessageStatusesRequestOuterClass.internal_static_im_turms_proto_CreateMessageStatusesRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return im.turms.turms.pojo.request.CreateMessageStatusesRequestOuterClass.internal_static_im_turms_proto_CreateMessageStatusesRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            im.turms.turms.pojo.request.CreateMessageStatusesRequest.class, im.turms.turms.pojo.request.CreateMessageStatusesRequest.Builder.class);
  }

  public static final int MESSAGE_ID_FIELD_NUMBER = 1;
  private long messageId_;
  /**
   * <code>int64 message_id = 1;</code>
   * @return The messageId.
   */
  public long getMessageId() {
    return messageId_;
  }

  public static final int CHAT_TYPE_FIELD_NUMBER = 2;
  private int chatType_;
  /**
   * <code>.im.turms.proto.ChatType chat_type = 2;</code>
   * @return The enum numeric value on the wire for chatType.
   */
  public int getChatTypeValue() {
    return chatType_;
  }
  /**
   * <code>.im.turms.proto.ChatType chat_type = 2;</code>
   * @return The chatType.
   */
  public im.turms.turms.constant.ChatType getChatType() {
    @SuppressWarnings("deprecation")
    im.turms.turms.constant.ChatType result = im.turms.turms.constant.ChatType.valueOf(chatType_);
    return result == null ? im.turms.turms.constant.ChatType.UNRECOGNIZED : result;
  }

  public static final int TO_ID_FIELD_NUMBER = 3;
  private long toId_;
  /**
   * <code>int64 to_id = 3;</code>
   * @return The toId.
   */
  public long getToId() {
    return toId_;
  }

  public static final int BURN_AFTER_FIELD_NUMBER = 4;
  private com.google.protobuf.Int32Value burnAfter_;
  /**
   * <code>.google.protobuf.Int32Value burn_after = 4;</code>
   * @return Whether the burnAfter field is set.
   */
  public boolean hasBurnAfter() {
    return burnAfter_ != null;
  }
  /**
   * <code>.google.protobuf.Int32Value burn_after = 4;</code>
   * @return The burnAfter.
   */
  public com.google.protobuf.Int32Value getBurnAfter() {
    return burnAfter_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : burnAfter_;
  }
  /**
   * <code>.google.protobuf.Int32Value burn_after = 4;</code>
   */
  public com.google.protobuf.Int32ValueOrBuilder getBurnAfterOrBuilder() {
    return getBurnAfter();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (messageId_ != 0L) {
      output.writeInt64(1, messageId_);
    }
    if (chatType_ != im.turms.turms.constant.ChatType.PRIVATE.getNumber()) {
      output.writeEnum(2, chatType_);
    }
    if (toId_ != 0L) {
      output.writeInt64(3, toId_);
    }
    if (burnAfter_ != null) {
      output.writeMessage(4, getBurnAfter());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (messageId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, messageId_);
    }
    if (chatType_ != im.turms.turms.constant.ChatType.PRIVATE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, chatType_);
    }
    if (toId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, toId_);
    }
    if (burnAfter_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getBurnAfter());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof im.turms.turms.pojo.request.CreateMessageStatusesRequest)) {
      return super.equals(obj);
    }
    im.turms.turms.pojo.request.CreateMessageStatusesRequest other = (im.turms.turms.pojo.request.CreateMessageStatusesRequest) obj;

    if (getMessageId()
        != other.getMessageId()) return false;
    if (chatType_ != other.chatType_) return false;
    if (getToId()
        != other.getToId()) return false;
    if (hasBurnAfter() != other.hasBurnAfter()) return false;
    if (hasBurnAfter()) {
      if (!getBurnAfter()
          .equals(other.getBurnAfter())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MESSAGE_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMessageId());
    hash = (37 * hash) + CHAT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + chatType_;
    hash = (37 * hash) + TO_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getToId());
    if (hasBurnAfter()) {
      hash = (37 * hash) + BURN_AFTER_FIELD_NUMBER;
      hash = (53 * hash) + getBurnAfter().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static im.turms.turms.pojo.request.CreateMessageStatusesRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static im.turms.turms.pojo.request.CreateMessageStatusesRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static im.turms.turms.pojo.request.CreateMessageStatusesRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static im.turms.turms.pojo.request.CreateMessageStatusesRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static im.turms.turms.pojo.request.CreateMessageStatusesRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static im.turms.turms.pojo.request.CreateMessageStatusesRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static im.turms.turms.pojo.request.CreateMessageStatusesRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static im.turms.turms.pojo.request.CreateMessageStatusesRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static im.turms.turms.pojo.request.CreateMessageStatusesRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static im.turms.turms.pojo.request.CreateMessageStatusesRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static im.turms.turms.pojo.request.CreateMessageStatusesRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static im.turms.turms.pojo.request.CreateMessageStatusesRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(im.turms.turms.pojo.request.CreateMessageStatusesRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code im.turms.proto.CreateMessageStatusesRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:im.turms.proto.CreateMessageStatusesRequest)
      im.turms.turms.pojo.request.CreateMessageStatusesRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return im.turms.turms.pojo.request.CreateMessageStatusesRequestOuterClass.internal_static_im_turms_proto_CreateMessageStatusesRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return im.turms.turms.pojo.request.CreateMessageStatusesRequestOuterClass.internal_static_im_turms_proto_CreateMessageStatusesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              im.turms.turms.pojo.request.CreateMessageStatusesRequest.class, im.turms.turms.pojo.request.CreateMessageStatusesRequest.Builder.class);
    }

    // Construct using im.turms.turms.pojo.request.CreateMessageStatusesRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      messageId_ = 0L;

      chatType_ = 0;

      toId_ = 0L;

      if (burnAfterBuilder_ == null) {
        burnAfter_ = null;
      } else {
        burnAfter_ = null;
        burnAfterBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return im.turms.turms.pojo.request.CreateMessageStatusesRequestOuterClass.internal_static_im_turms_proto_CreateMessageStatusesRequest_descriptor;
    }

    @java.lang.Override
    public im.turms.turms.pojo.request.CreateMessageStatusesRequest getDefaultInstanceForType() {
      return im.turms.turms.pojo.request.CreateMessageStatusesRequest.getDefaultInstance();
    }

    @java.lang.Override
    public im.turms.turms.pojo.request.CreateMessageStatusesRequest build() {
      im.turms.turms.pojo.request.CreateMessageStatusesRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public im.turms.turms.pojo.request.CreateMessageStatusesRequest buildPartial() {
      im.turms.turms.pojo.request.CreateMessageStatusesRequest result = new im.turms.turms.pojo.request.CreateMessageStatusesRequest(this);
      result.messageId_ = messageId_;
      result.chatType_ = chatType_;
      result.toId_ = toId_;
      if (burnAfterBuilder_ == null) {
        result.burnAfter_ = burnAfter_;
      } else {
        result.burnAfter_ = burnAfterBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof im.turms.turms.pojo.request.CreateMessageStatusesRequest) {
        return mergeFrom((im.turms.turms.pojo.request.CreateMessageStatusesRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(im.turms.turms.pojo.request.CreateMessageStatusesRequest other) {
      if (other == im.turms.turms.pojo.request.CreateMessageStatusesRequest.getDefaultInstance()) return this;
      if (other.getMessageId() != 0L) {
        setMessageId(other.getMessageId());
      }
      if (other.chatType_ != 0) {
        setChatTypeValue(other.getChatTypeValue());
      }
      if (other.getToId() != 0L) {
        setToId(other.getToId());
      }
      if (other.hasBurnAfter()) {
        mergeBurnAfter(other.getBurnAfter());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      im.turms.turms.pojo.request.CreateMessageStatusesRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (im.turms.turms.pojo.request.CreateMessageStatusesRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long messageId_ ;
    /**
     * <code>int64 message_id = 1;</code>
     * @return The messageId.
     */
    public long getMessageId() {
      return messageId_;
    }
    /**
     * <code>int64 message_id = 1;</code>
     * @param value The messageId to set.
     * @return This builder for chaining.
     */
    public Builder setMessageId(long value) {
      
      messageId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 message_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageId() {
      
      messageId_ = 0L;
      onChanged();
      return this;
    }

    private int chatType_ = 0;
    /**
     * <code>.im.turms.proto.ChatType chat_type = 2;</code>
     * @return The enum numeric value on the wire for chatType.
     */
    public int getChatTypeValue() {
      return chatType_;
    }
    /**
     * <code>.im.turms.proto.ChatType chat_type = 2;</code>
     * @param value The enum numeric value on the wire for chatType to set.
     * @return This builder for chaining.
     */
    public Builder setChatTypeValue(int value) {
      chatType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.im.turms.proto.ChatType chat_type = 2;</code>
     * @return The chatType.
     */
    public im.turms.turms.constant.ChatType getChatType() {
      @SuppressWarnings("deprecation")
      im.turms.turms.constant.ChatType result = im.turms.turms.constant.ChatType.valueOf(chatType_);
      return result == null ? im.turms.turms.constant.ChatType.UNRECOGNIZED : result;
    }
    /**
     * <code>.im.turms.proto.ChatType chat_type = 2;</code>
     * @param value The chatType to set.
     * @return This builder for chaining.
     */
    public Builder setChatType(im.turms.turms.constant.ChatType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      chatType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.im.turms.proto.ChatType chat_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearChatType() {
      
      chatType_ = 0;
      onChanged();
      return this;
    }

    private long toId_ ;
    /**
     * <code>int64 to_id = 3;</code>
     * @return The toId.
     */
    public long getToId() {
      return toId_;
    }
    /**
     * <code>int64 to_id = 3;</code>
     * @param value The toId to set.
     * @return This builder for chaining.
     */
    public Builder setToId(long value) {
      
      toId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 to_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearToId() {
      
      toId_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.Int32Value burnAfter_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> burnAfterBuilder_;
    /**
     * <code>.google.protobuf.Int32Value burn_after = 4;</code>
     * @return Whether the burnAfter field is set.
     */
    public boolean hasBurnAfter() {
      return burnAfterBuilder_ != null || burnAfter_ != null;
    }
    /**
     * <code>.google.protobuf.Int32Value burn_after = 4;</code>
     * @return The burnAfter.
     */
    public com.google.protobuf.Int32Value getBurnAfter() {
      if (burnAfterBuilder_ == null) {
        return burnAfter_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : burnAfter_;
      } else {
        return burnAfterBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int32Value burn_after = 4;</code>
     */
    public Builder setBurnAfter(com.google.protobuf.Int32Value value) {
      if (burnAfterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        burnAfter_ = value;
        onChanged();
      } else {
        burnAfterBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value burn_after = 4;</code>
     */
    public Builder setBurnAfter(
        com.google.protobuf.Int32Value.Builder builderForValue) {
      if (burnAfterBuilder_ == null) {
        burnAfter_ = builderForValue.build();
        onChanged();
      } else {
        burnAfterBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value burn_after = 4;</code>
     */
    public Builder mergeBurnAfter(com.google.protobuf.Int32Value value) {
      if (burnAfterBuilder_ == null) {
        if (burnAfter_ != null) {
          burnAfter_ =
            com.google.protobuf.Int32Value.newBuilder(burnAfter_).mergeFrom(value).buildPartial();
        } else {
          burnAfter_ = value;
        }
        onChanged();
      } else {
        burnAfterBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value burn_after = 4;</code>
     */
    public Builder clearBurnAfter() {
      if (burnAfterBuilder_ == null) {
        burnAfter_ = null;
        onChanged();
      } else {
        burnAfter_ = null;
        burnAfterBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value burn_after = 4;</code>
     */
    public com.google.protobuf.Int32Value.Builder getBurnAfterBuilder() {
      
      onChanged();
      return getBurnAfterFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int32Value burn_after = 4;</code>
     */
    public com.google.protobuf.Int32ValueOrBuilder getBurnAfterOrBuilder() {
      if (burnAfterBuilder_ != null) {
        return burnAfterBuilder_.getMessageOrBuilder();
      } else {
        return burnAfter_ == null ?
            com.google.protobuf.Int32Value.getDefaultInstance() : burnAfter_;
      }
    }
    /**
     * <code>.google.protobuf.Int32Value burn_after = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> 
        getBurnAfterFieldBuilder() {
      if (burnAfterBuilder_ == null) {
        burnAfterBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                getBurnAfter(),
                getParentForChildren(),
                isClean());
        burnAfter_ = null;
      }
      return burnAfterBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:im.turms.proto.CreateMessageStatusesRequest)
  }

  // @@protoc_insertion_point(class_scope:im.turms.proto.CreateMessageStatusesRequest)
  private static final im.turms.turms.pojo.request.CreateMessageStatusesRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new im.turms.turms.pojo.request.CreateMessageStatusesRequest();
  }

  public static im.turms.turms.pojo.request.CreateMessageStatusesRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateMessageStatusesRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreateMessageStatusesRequest>() {
    @java.lang.Override
    public CreateMessageStatusesRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateMessageStatusesRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateMessageStatusesRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateMessageStatusesRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public im.turms.turms.pojo.request.CreateMessageStatusesRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

