// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request/message/create_message_statuses_request.proto

package im.turms.turms.pojo.request;

public final class CreateMessageStatusesRequestOuterClass {
  private CreateMessageStatusesRequestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_turms_proto_CreateMessageStatusesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_turms_proto_CreateMessageStatusesRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n5request/message/create_message_statuse" +
      "s_request.proto\022\016im.turms.proto\032\036google/" +
      "protobuf/wrappers.proto\032\030constant/chat_t" +
      "ype.proto\"\237\001\n\034CreateMessageStatusesReque" +
      "st\022\022\n\nmessage_id\030\001 \001(\003\022+\n\tchat_type\030\002 \001(" +
      "\0162\030.im.turms.proto.ChatType\022\r\n\005to_id\030\003 \001" +
      "(\003\022/\n\nburn_after\030\004 \001(\0132\033.google.protobuf" +
      ".Int32ValueB\037\n\033im.turms.turms.pojo.reque" +
      "stP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          im.turms.turms.constant.ChatTypeOuterClass.getDescriptor(),
        });
    internal_static_im_turms_proto_CreateMessageStatusesRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_im_turms_proto_CreateMessageStatusesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_turms_proto_CreateMessageStatusesRequest_descriptor,
        new java.lang.String[] { "MessageId", "ChatType", "ToId", "BurnAfter", });
    com.google.protobuf.WrappersProto.getDescriptor();
    im.turms.turms.constant.ChatTypeOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
