// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request/message/create_message_request.proto

package im.turms.turms.pojo.request;

public interface CreateMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:im.turms.proto.CreateMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.im.turms.proto.ChatType chat_type = 1;</code>
   * @return The enum numeric value on the wire for chatType.
   */
  int getChatTypeValue();
  /**
   * <code>.im.turms.proto.ChatType chat_type = 1;</code>
   * @return The chatType.
   */
  im.turms.turms.constant.ChatType getChatType();

  /**
   * <code>int64 to_id = 2;</code>
   * @return The toId.
   */
  long getToId();

  /**
   * <code>int64 delivery_date = 3;</code>
   * @return The deliveryDate.
   */
  long getDeliveryDate();

  /**
   * <code>string text = 4;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>string text = 4;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <code>repeated bytes records = 5;</code>
   * @return A list containing the records.
   */
  java.util.List<com.google.protobuf.ByteString> getRecordsList();
  /**
   * <code>repeated bytes records = 5;</code>
   * @return The count of records.
   */
  int getRecordsCount();
  /**
   * <code>repeated bytes records = 5;</code>
   * @param index The index of the element to return.
   * @return The records at the given index.
   */
  com.google.protobuf.ByteString getRecords(int index);

  /**
   * <code>.google.protobuf.Int32Value burn_after = 6;</code>
   * @return Whether the burnAfter field is set.
   */
  boolean hasBurnAfter();
  /**
   * <code>.google.protobuf.Int32Value burn_after = 6;</code>
   * @return The burnAfter.
   */
  com.google.protobuf.Int32Value getBurnAfter();
  /**
   * <code>.google.protobuf.Int32Value burn_after = 6;</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getBurnAfterOrBuilder();
}
