// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request/group/delete_group_request.proto

package im.turms.turms.pojo.request;

public interface DeleteGroupRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:im.turms.proto.DeleteGroupRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 group_id = 1;</code>
   * @return The groupId.
   */
  long getGroupId();
}
