// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request/message/query_message_status_request.proto

package im.turms.turms.pojo.request;

public final class QueryMessageStatusRequestOuterClass {
  private QueryMessageStatusRequestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_turms_proto_QueryMessageStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_turms_proto_QueryMessageStatusRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n2request/message/query_message_status_r" +
      "equest.proto\022\016im.turms.proto\"/\n\031QueryMes" +
      "sageStatusRequest\022\022\n\nmessage_id\030\001 \001(\003B\037\n" +
      "\033im.turms.turms.pojo.requestP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_im_turms_proto_QueryMessageStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_im_turms_proto_QueryMessageStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_turms_proto_QueryMessageStatusRequest_descriptor,
        new java.lang.String[] { "MessageId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
