// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request/turms_request.proto

package im.turms.turms.pojo.request;

public final class TurmsRequestOuterClass {
  private TurmsRequestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_turms_proto_TurmsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_turms_proto_TurmsRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033request/turms_request.proto\022\016im.turms." +
      "proto\032\036google/protobuf/wrappers.proto\032 r" +
      "equest/signal/ack_request.proto\0327request" +
      "/user/query_user_group_invitations_reque" +
      "st.proto\032-request/user/query_user_profil" +
      "e_request.proto\0321request/user/query_user" +
      "s_ids_nearby_request.proto\0323request/user" +
      "/query_users_infos_nearby_request.proto\032" +
      "4request/user/query_users_online_status_" +
      "request.proto\032/request/user/update_user_" +
      "location_request.proto\0324request/user/upd" +
      "ate_user_online_status_request.proto\032&re" +
      "quest/user/update_user_request.proto\032=re" +
      "quest/user/relationship/create_friend_re" +
      "quest_request.proto\032Arequest/user/relati" +
      "onship/create_relationship_group_request" +
      ".proto\032;request/user/relationship/create" +
      "_relationship_request.proto\032Arequest/use" +
      "r/relationship/delete_relationship_group" +
      "_request.proto\032;request/user/relationshi" +
      "p/delete_relationship_request.proto\032=req" +
      "uest/user/relationship/query_friend_requ" +
      "ests_request.proto\032?request/user/relatio" +
      "nship/query_related_users_ids_request.pr" +
      "oto\032Arequest/user/relationship/query_rel" +
      "ationship_groups_request.proto\032;request/" +
      "user/relationship/query_relationships_re" +
      "quest.proto\032=request/user/relationship/u" +
      "pdate_friend_request_request.proto\032Arequ" +
      "est/user/relationship/update_relationshi" +
      "p_group_request.proto\032;request/user/rela" +
      "tionship/update_relationship_request.pro" +
      "to\032(request/group/create_group_request.p" +
      "roto\032(request/group/delete_group_request" +
      ".proto\032\'request/group/query_group_reques" +
      "t.proto\0323request/group/query_joined_grou" +
      "ps_ids_request.proto\0325request/group/quer" +
      "y_joined_groups_infos_request.proto\032(req" +
      "uest/group/update_group_request.proto\032Cr" +
      "equest/group/blacklist/create_group_blac" +
      "klisted_user_request.proto\032Crequest/grou" +
      "p/blacklist/delete_group_blacklisted_use" +
      "r_request.proto\032Grequest/group/blacklist" +
      "/query_group_blacklisted_users_ids_reque" +
      "st.proto\032Irequest/group/blacklist/query_" +
      "group_blacklisted_users_infos_request.pr" +
      "oto\032Grequest/group/enrollment/check_grou" +
      "p_join_question_answer_request.proto\032>re" +
      "quest/group/enrollment/create_group_invi" +
      "tation_request.proto\032@request/group/enro" +
      "llment/create_group_join_request_request" +
      ".proto\032Arequest/group/enrollment/create_" +
      "group_join_question_request.proto\032>reque" +
      "st/group/enrollment/delete_group_invitat" +
      "ion_request.proto\032@request/group/enrollm" +
      "ent/delete_group_join_request_request.pr" +
      "oto\032Arequest/group/enrollment/delete_gro" +
      "up_join_question_request.proto\032>request/" +
      "group/enrollment/query_group_invitations" +
      "_request.proto\032@request/group/enrollment" +
      "/query_group_join_requests_request.proto" +
      "\032Arequest/group/enrollment/query_group_j" +
      "oin_questions_request.proto\032Arequest/gro" +
      "up/enrollment/update_group_join_question" +
      "_request.proto\0326request/group/member/cre" +
      "ate_group_member_request.proto\0326request/" +
      "group/member/delete_group_member_request" +
      ".proto\0326request/group/member/query_group" +
      "_members_request.proto\0326request/group/me" +
      "mber/update_group_member_request.proto\032," +
      "request/message/create_message_request.p" +
      "roto\0324request/message/query_message_stat" +
      "uses_request.proto\032,request/message/quer" +
      "y_messages_request.proto\032?request/messag" +
      "e/query_pending_messages_with_total_requ" +
      "est.proto\032,request/message/update_messag" +
      "e_request.proto\0322request/message/update_" +
      "typing_status_request.proto\"\250$\n\014TurmsReq" +
      "uest\022/\n\nrequest_id\030\001 \001(\0132\033.google.protob" +
      "uf.Int64Value\0221\n\014requester_id\030\002 \001(\0132\033.go" +
      "ogle.protobuf.Int64Value\0221\n\013ack_request\030" +
      "\003 \001(\0132\032.im.turms.proto.AckRequestH\000\022F\n\026c" +
      "reate_message_request\030\005 \001(\0132$.im.turms.p" +
      "roto.CreateMessageRequestH\000\022U\n\036query_mes" +
      "sage_statuses_request\030\006 \001(\0132+.im.turms.p" +
      "roto.QueryMessageStatusesRequestH\000\022F\n\026qu" +
      "ery_messages_request\030\007 \001(\0132$.im.turms.pr" +
      "oto.QueryMessagesRequestH\000\022i\n)query_pend" +
      "ing_messages_with_total_request\030\010 \001(\01324." +
      "im.turms.proto.QueryPendingMessagesWithT" +
      "otalRequestH\000\022F\n\026update_message_request\030" +
      "\t \001(\0132$.im.turms.proto.UpdateMessageRequ" +
      "estH\000\022Q\n\034update_typing_status_request\030\n " +
      "\001(\0132).im.turms.proto.UpdateTypingStatusR" +
      "equestH\000\022`\n$query_user_group_invitations" +
      "_request\030d \001(\01320.im.turms.proto.QueryUse" +
      "rGroupInvitationsRequestH\000\022M\n\032query_user" +
      "_profile_request\030e \001(\0132\'.im.turms.proto." +
      "QueryUserProfileRequestH\000\022T\n\036query_users" +
      "_ids_nearby_request\030f \001(\0132*.im.turms.pro" +
      "to.QueryUsersIdsNearbyRequestH\000\022X\n query" +
      "_users_infos_nearby_request\030g \001(\0132,.im.t" +
      "urms.proto.QueryUsersInfosNearbyRequestH" +
      "\000\022Z\n!query_users_online_status_request\030h" +
      " \001(\0132-.im.turms.proto.QueryUsersOnlineSt" +
      "atusRequestH\000\022Q\n\034update_user_location_re" +
      "quest\030i \001(\0132).im.turms.proto.UpdateUserL" +
      "ocationRequestH\000\022Z\n!update_user_online_s" +
      "tatus_request\030j \001(\0132-.im.turms.proto.Upd" +
      "ateUserOnlineStatusRequestH\000\022@\n\023update_u" +
      "ser_request\030k \001(\0132!.im.turms.proto.Updat" +
      "eUserRequestH\000\022T\n\035create_friend_request_" +
      "request\030\310\001 \001(\0132*.im.turms.proto.CreateFr" +
      "iendRequestRequestH\000\022\\\n!create_relations" +
      "hip_group_request\030\311\001 \001(\0132..im.turms.prot" +
      "o.CreateRelationshipGroupRequestH\000\022Q\n\033cr" +
      "eate_relationship_request\030\312\001 \001(\0132).im.tu" +
      "rms.proto.CreateRelationshipRequestH\000\022\\\n" +
      "!delete_relationship_group_request\030\313\001 \001(" +
      "\0132..im.turms.proto.DeleteRelationshipGro" +
      "upRequestH\000\022Q\n\033delete_relationship_reque" +
      "st\030\314\001 \001(\0132).im.turms.proto.DeleteRelatio" +
      "nshipRequestH\000\022T\n\035query_friend_requests_" +
      "request\030\315\001 \001(\0132*.im.turms.proto.QueryFri" +
      "endRequestsRequestH\000\022W\n\037query_related_us" +
      "ers_ids_request\030\316\001 \001(\0132+.im.turms.proto." +
      "QueryRelatedUsersIdsRequestH\000\022\\\n!query_r" +
      "elationship_groups_request\030\317\001 \001(\0132..im.t" +
      "urms.proto.QueryRelationshipGroupsReques" +
      "tH\000\022Q\n\033query_relationships_request\030\320\001 \001(" +
      "\0132).im.turms.proto.QueryRelationshipsReq" +
      "uestH\000\022T\n\035update_friend_request_request\030" +
      "\321\001 \001(\0132*.im.turms.proto.UpdateFriendRequ" +
      "estRequestH\000\022\\\n!update_relationship_grou" +
      "p_request\030\322\001 \001(\0132..im.turms.proto.Update" +
      "RelationshipGroupRequestH\000\022Q\n\033update_rel" +
      "ationship_request\030\323\001 \001(\0132).im.turms.prot" +
      "o.UpdateRelationshipRequestH\000\022C\n\024create_" +
      "group_request\030\254\002 \001(\0132\".im.turms.proto.Cr" +
      "eateGroupRequestH\000\022C\n\024delete_group_reque" +
      "st\030\255\002 \001(\0132\".im.turms.proto.DeleteGroupRe" +
      "questH\000\022A\n\023query_group_request\030\256\002 \001(\0132!." +
      "im.turms.proto.QueryGroupRequestH\000\022W\n\037qu" +
      "ery_joined_groups_ids_request\030\257\002 \001(\0132+.i" +
      "m.turms.proto.QueryJoinedGroupsIdsReques" +
      "tH\000\022[\n!query_joined_groups_infos_request" +
      "\030\260\002 \001(\0132-.im.turms.proto.QueryJoinedGrou" +
      "psInfosRequestH\000\022C\n\024update_group_request" +
      "\030\261\002 \001(\0132\".im.turms.proto.UpdateGroupRequ" +
      "estH\000\022c\n%create_group_blacklisted_user_r" +
      "equest\030\220\003 \001(\01321.im.turms.proto.CreateGro" +
      "upBlacklistedUserRequestH\000\022c\n%delete_gro" +
      "up_blacklisted_user_request\030\221\003 \001(\01321.im." +
      "turms.proto.DeleteGroupBlacklistedUserRe" +
      "questH\000\022j\n)query_group_blacklisted_users" +
      "_ids_request\030\222\003 \001(\01324.im.turms.proto.Que" +
      "ryGroupBlacklistedUsersIdsRequestH\000\022n\n+q" +
      "uery_group_blacklisted_users_infos_reque" +
      "st\030\223\003 \001(\01326.im.turms.proto.QueryGroupBla" +
      "cklistedUsersInfosRequestH\000\022h\n(check_gro" +
      "up_join_question_answer_request\030\364\003 \001(\01323" +
      ".im.turms.proto.CheckGroupJoinQuestionAn" +
      "swerRequestH\000\022X\n\037create_group_invitation" +
      "_request\030\365\003 \001(\0132,.im.turms.proto.CreateG" +
      "roupInvitationRequestH\000\022[\n!create_group_" +
      "join_request_request\030\366\003 \001(\0132-.im.turms.p" +
      "roto.CreateGroupJoinRequestRequestH\000\022]\n\"" +
      "create_group_join_question_request\030\367\003 \001(" +
      "\0132..im.turms.proto.CreateGroupJoinQuesti" +
      "onRequestH\000\022X\n\037delete_group_invitation_r" +
      "equest\030\370\003 \001(\0132,.im.turms.proto.DeleteGro" +
      "upInvitationRequestH\000\022[\n!delete_group_jo" +
      "in_request_request\030\371\003 \001(\0132-.im.turms.pro" +
      "to.DeleteGroupJoinRequestRequestH\000\022]\n\"de" +
      "lete_group_join_question_request\030\372\003 \001(\0132" +
      "..im.turms.proto.DeleteGroupJoinQuestion" +
      "RequestH\000\022X\n\037query_group_invitations_req" +
      "uest\030\373\003 \001(\0132,.im.turms.proto.QueryGroupI" +
      "nvitationsRequestH\000\022[\n!query_group_join_" +
      "requests_request\030\374\003 \001(\0132-.im.turms.proto" +
      ".QueryGroupJoinRequestsRequestH\000\022]\n\"quer" +
      "y_group_join_questions_request\030\375\003 \001(\0132.." +
      "im.turms.proto.QueryGroupJoinQuestionsRe" +
      "questH\000\022]\n\"update_group_join_question_re" +
      "quest\030\376\003 \001(\0132..im.turms.proto.UpdateGrou" +
      "pJoinQuestionRequestH\000\022P\n\033create_group_m" +
      "ember_request\030\330\004 \001(\0132(.im.turms.proto.Cr" +
      "eateGroupMemberRequestH\000\022P\n\033delete_group" +
      "_member_request\030\331\004 \001(\0132(.im.turms.proto." +
      "DeleteGroupMemberRequestH\000\022P\n\033query_grou" +
      "p_members_request\030\332\004 \001(\0132(.im.turms.prot" +
      "o.QueryGroupMembersRequestH\000\022P\n\033update_g" +
      "roup_member_request\030\333\004 \001(\0132(.im.turms.pr" +
      "oto.UpdateGroupMemberRequestH\000B\006\n\004kindB\037" +
      "\n\033im.turms.turms.pojo.requestP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          im.turms.turms.pojo.request.AckRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.QueryUserGroupInvitationsRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.QueryUserProfileRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.QueryUsersIdsNearbyRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.QueryUsersInfosNearbyRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.QueryUsersOnlineStatusRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.UpdateUserLocationRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.UpdateUserOnlineStatusRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.UpdateUserRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.CreateFriendRequestRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.CreateRelationshipGroupRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.CreateRelationshipRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.DeleteRelationshipGroupRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.DeleteRelationshipRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.QueryFriendRequestsRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.QueryRelatedUsersIdsRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.QueryRelationshipGroupsRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.QueryRelationshipsRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.UpdateFriendRequestRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.UpdateRelationshipGroupRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.UpdateRelationshipRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.CreateGroupRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.DeleteGroupRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.QueryGroupRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.QueryJoinedGroupsIdsRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.QueryJoinedGroupsInfosRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.UpdateGroupRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.CreateGroupBlacklistedUserRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.DeleteGroupBlacklistedUserRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.QueryGroupBlacklistedUsersIdsRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.QueryGroupBlacklistedUsersInfosRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.CreateGroupInvitationRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.CreateGroupJoinRequestRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.CreateGroupJoinQuestionRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.DeleteGroupInvitationRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.DeleteGroupJoinRequestRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.DeleteGroupJoinQuestionRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.QueryGroupInvitationsRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.QueryGroupJoinRequestsRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.QueryGroupJoinQuestionsRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.UpdateGroupJoinQuestionRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.CreateGroupMemberRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.DeleteGroupMemberRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.QueryGroupMembersRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.UpdateGroupMemberRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.CreateMessageRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.QueryMessageStatusesRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.QueryMessagesRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.QueryPendingMessagesWithTotalRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.UpdateMessageRequestOuterClass.getDescriptor(),
          im.turms.turms.pojo.request.UpdateTypingStatusRequestOuterClass.getDescriptor(),
        });
    internal_static_im_turms_proto_TurmsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_im_turms_proto_TurmsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_turms_proto_TurmsRequest_descriptor,
        new java.lang.String[] { "RequestId", "RequesterId", "AckRequest", "CreateMessageRequest", "QueryMessageStatusesRequest", "QueryMessagesRequest", "QueryPendingMessagesWithTotalRequest", "UpdateMessageRequest", "UpdateTypingStatusRequest", "QueryUserGroupInvitationsRequest", "QueryUserProfileRequest", "QueryUsersIdsNearbyRequest", "QueryUsersInfosNearbyRequest", "QueryUsersOnlineStatusRequest", "UpdateUserLocationRequest", "UpdateUserOnlineStatusRequest", "UpdateUserRequest", "CreateFriendRequestRequest", "CreateRelationshipGroupRequest", "CreateRelationshipRequest", "DeleteRelationshipGroupRequest", "DeleteRelationshipRequest", "QueryFriendRequestsRequest", "QueryRelatedUsersIdsRequest", "QueryRelationshipGroupsRequest", "QueryRelationshipsRequest", "UpdateFriendRequestRequest", "UpdateRelationshipGroupRequest", "UpdateRelationshipRequest", "CreateGroupRequest", "DeleteGroupRequest", "QueryGroupRequest", "QueryJoinedGroupsIdsRequest", "QueryJoinedGroupsInfosRequest", "UpdateGroupRequest", "CreateGroupBlacklistedUserRequest", "DeleteGroupBlacklistedUserRequest", "QueryGroupBlacklistedUsersIdsRequest", "QueryGroupBlacklistedUsersInfosRequest", "CheckGroupJoinQuestionAnswerRequest", "CreateGroupInvitationRequest", "CreateGroupJoinRequestRequest", "CreateGroupJoinQuestionRequest", "DeleteGroupInvitationRequest", "DeleteGroupJoinRequestRequest", "DeleteGroupJoinQuestionRequest", "QueryGroupInvitationsRequest", "QueryGroupJoinRequestsRequest", "QueryGroupJoinQuestionsRequest", "UpdateGroupJoinQuestionRequest", "CreateGroupMemberRequest", "DeleteGroupMemberRequest", "QueryGroupMembersRequest", "UpdateGroupMemberRequest", "Kind", });
    com.google.protobuf.WrappersProto.getDescriptor();
    im.turms.turms.pojo.request.AckRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.QueryUserGroupInvitationsRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.QueryUserProfileRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.QueryUsersIdsNearbyRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.QueryUsersInfosNearbyRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.QueryUsersOnlineStatusRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.UpdateUserLocationRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.UpdateUserOnlineStatusRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.UpdateUserRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.CreateFriendRequestRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.CreateRelationshipGroupRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.CreateRelationshipRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.DeleteRelationshipGroupRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.DeleteRelationshipRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.QueryFriendRequestsRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.QueryRelatedUsersIdsRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.QueryRelationshipGroupsRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.QueryRelationshipsRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.UpdateFriendRequestRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.UpdateRelationshipGroupRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.UpdateRelationshipRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.CreateGroupRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.DeleteGroupRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.QueryGroupRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.QueryJoinedGroupsIdsRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.QueryJoinedGroupsInfosRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.UpdateGroupRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.CreateGroupBlacklistedUserRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.DeleteGroupBlacklistedUserRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.QueryGroupBlacklistedUsersIdsRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.QueryGroupBlacklistedUsersInfosRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.CheckGroupJoinQuestionAnswerRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.CreateGroupInvitationRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.CreateGroupJoinRequestRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.CreateGroupJoinQuestionRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.DeleteGroupInvitationRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.DeleteGroupJoinRequestRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.DeleteGroupJoinQuestionRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.QueryGroupInvitationsRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.QueryGroupJoinRequestsRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.QueryGroupJoinQuestionsRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.UpdateGroupJoinQuestionRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.CreateGroupMemberRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.DeleteGroupMemberRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.QueryGroupMembersRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.UpdateGroupMemberRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.CreateMessageRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.QueryMessageStatusesRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.QueryMessagesRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.QueryPendingMessagesWithTotalRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.UpdateMessageRequestOuterClass.getDescriptor();
    im.turms.turms.pojo.request.UpdateTypingStatusRequestOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
