// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request/message/update_message_request.proto

package im.turms.turms.pojo.request;

public final class UpdateMessageRequestOuterClass {
  private UpdateMessageRequestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_im_turms_proto_UpdateMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_im_turms_proto_UpdateMessageRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,request/message/update_message_request" +
      ".proto\022\016im.turms.proto\032\036google/protobuf/" +
      "wrappers.proto\"\307\001\n\024UpdateMessageRequest\022" +
      "\022\n\nmessage_id\030\001 \001(\003\022*\n\004text\030\002 \001(\0132\034.goog" +
      "le.protobuf.StringValue\022\017\n\007records\030\003 \003(\014" +
      "\022/\n\nrecallDate\030\004 \001(\0132\033.google.protobuf.I" +
      "nt64Value\022-\n\010readDate\030\005 \001(\0132\033.google.pro" +
      "tobuf.Int64ValueB\037\n\033im.turms.turms.pojo." +
      "requestP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_im_turms_proto_UpdateMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_im_turms_proto_UpdateMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_im_turms_proto_UpdateMessageRequest_descriptor,
        new java.lang.String[] { "MessageId", "Text", "Records", "RecallDate", "ReadDate", });
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
