// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request/message/query_messages_request.proto

package im.turms.turms.pojo.request.message;

/**
 * Protobuf type {@code im.turms.proto.QueryMessagesRequest}
 */
public  final class QueryMessagesRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:im.turms.proto.QueryMessagesRequest)
    QueryMessagesRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use QueryMessagesRequest.newBuilder() to construct.
  private QueryMessagesRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private QueryMessagesRequest() {
    chatType_ = 0;
    deliveryStatus_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new QueryMessagesRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private QueryMessagesRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.Int32Value.Builder subBuilder = null;
            if (size_ != null) {
              subBuilder = size_.toBuilder();
            }
            size_ = input.readMessage(com.google.protobuf.Int32Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(size_);
              size_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            chatType_ = rawValue;
            break;
          }
          case 26: {
            com.google.protobuf.Int64Value.Builder subBuilder = null;
            if (fromId_ != null) {
              subBuilder = fromId_.toBuilder();
            }
            fromId_ = input.readMessage(com.google.protobuf.Int64Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(fromId_);
              fromId_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.google.protobuf.Int64Value.Builder subBuilder = null;
            if (deliveryDateAfter_ != null) {
              subBuilder = deliveryDateAfter_.toBuilder();
            }
            deliveryDateAfter_ = input.readMessage(com.google.protobuf.Int64Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(deliveryDateAfter_);
              deliveryDateAfter_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            com.google.protobuf.Int64Value.Builder subBuilder = null;
            if (deliveryDateBefore_ != null) {
              subBuilder = deliveryDateBefore_.toBuilder();
            }
            deliveryDateBefore_ = input.readMessage(com.google.protobuf.Int64Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(deliveryDateBefore_);
              deliveryDateBefore_ = subBuilder.buildPartial();
            }

            break;
          }
          case 48: {
            int rawValue = input.readEnum();

            deliveryStatus_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  // @@protoc_insertion_point(class_scope:im.turms.proto.QueryMessagesRequest)
  private static final im.turms.turms.pojo.request.message.QueryMessagesRequest DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new im.turms.turms.pojo.request.message.QueryMessagesRequest();
  }

  public static final int SIZE_FIELD_NUMBER = 1;
  private com.google.protobuf.Int32Value size_;

  /**
   * <code>.google.protobuf.Int32Value size = 1;</code>
   *
   * @return Whether the size field is set.
   */
  public boolean hasSize() {
    return size_ != null;
  }
  /**
   * <code>.google.protobuf.Int32Value size = 1;</code>
   * @return The size.
   */
  public com.google.protobuf.Int32Value getSize() {
    return size_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : size_;
  }
  /**
   * <code>.google.protobuf.Int32Value size = 1;</code>
   */
  public com.google.protobuf.Int32ValueOrBuilder getSizeOrBuilder() {
    return getSize();
  }

  public static final int CHAT_TYPE_FIELD_NUMBER = 2;
  private int chatType_;
  /**
   * <code>.im.turms.proto.ChatType chat_type = 2;</code>
   * @return The enum numeric value on the wire for chatType.
   */
  public int getChatTypeValue() {
    return chatType_;
  }
  /**
   * <code>.im.turms.proto.ChatType chat_type = 2;</code>
   * @return The chatType.
   */
  public im.turms.turms.constant.ChatType getChatType() {
    @SuppressWarnings("deprecation")
    im.turms.turms.constant.ChatType result = im.turms.turms.constant.ChatType.valueOf(chatType_);
    return result == null ? im.turms.turms.constant.ChatType.UNRECOGNIZED : result;
  }

  public static final int FROM_ID_FIELD_NUMBER = 3;
  private com.google.protobuf.Int64Value fromId_;
  /**
   * <code>.google.protobuf.Int64Value from_id = 3;</code>
   * @return Whether the fromId field is set.
   */
  public boolean hasFromId() {
    return fromId_ != null;
  }
  /**
   * <code>.google.protobuf.Int64Value from_id = 3;</code>
   * @return The fromId.
   */
  public com.google.protobuf.Int64Value getFromId() {
    return fromId_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : fromId_;
  }
  /**
   * <code>.google.protobuf.Int64Value from_id = 3;</code>
   */
  public com.google.protobuf.Int64ValueOrBuilder getFromIdOrBuilder() {
    return getFromId();
  }

  public static final int DELIVERY_DATE_AFTER_FIELD_NUMBER = 4;
  private com.google.protobuf.Int64Value deliveryDateAfter_;
  /**
   * <code>.google.protobuf.Int64Value delivery_date_after = 4;</code>
   * @return Whether the deliveryDateAfter field is set.
   */
  public boolean hasDeliveryDateAfter() {
    return deliveryDateAfter_ != null;
  }
  /**
   * <code>.google.protobuf.Int64Value delivery_date_after = 4;</code>
   * @return The deliveryDateAfter.
   */
  public com.google.protobuf.Int64Value getDeliveryDateAfter() {
    return deliveryDateAfter_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : deliveryDateAfter_;
  }
  /**
   * <code>.google.protobuf.Int64Value delivery_date_after = 4;</code>
   */
  public com.google.protobuf.Int64ValueOrBuilder getDeliveryDateAfterOrBuilder() {
    return getDeliveryDateAfter();
  }

  public static final int DELIVERY_DATE_BEFORE_FIELD_NUMBER = 5;
  private com.google.protobuf.Int64Value deliveryDateBefore_;
  /**
   * <code>.google.protobuf.Int64Value delivery_date_before = 5;</code>
   * @return Whether the deliveryDateBefore field is set.
   */
  public boolean hasDeliveryDateBefore() {
    return deliveryDateBefore_ != null;
  }
  /**
   * <code>.google.protobuf.Int64Value delivery_date_before = 5;</code>
   * @return The deliveryDateBefore.
   */
  public com.google.protobuf.Int64Value getDeliveryDateBefore() {
    return deliveryDateBefore_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : deliveryDateBefore_;
  }
  /**
   * <code>.google.protobuf.Int64Value delivery_date_before = 5;</code>
   */
  public com.google.protobuf.Int64ValueOrBuilder getDeliveryDateBeforeOrBuilder() {
    return getDeliveryDateBefore();
  }

  public static final int DELIVERY_STATUS_FIELD_NUMBER = 6;
  private int deliveryStatus_;
  /**
   * <code>.im.turms.proto.MessageDeliveryStatus delivery_status = 6;</code>
   * @return The enum numeric value on the wire for deliveryStatus.
   */
  public int getDeliveryStatusValue() {
    return deliveryStatus_;
  }
  /**
   * <code>.im.turms.proto.MessageDeliveryStatus delivery_status = 6;</code>
   * @return The deliveryStatus.
   */
  public im.turms.turms.constant.MessageDeliveryStatus getDeliveryStatus() {
    @SuppressWarnings("deprecation")
    im.turms.turms.constant.MessageDeliveryStatus result = im.turms.turms.constant.MessageDeliveryStatus.valueOf(deliveryStatus_);
    return result == null ? im.turms.turms.constant.MessageDeliveryStatus.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (size_ != null) {
      output.writeMessage(1, getSize());
    }
    if (chatType_ != im.turms.turms.constant.ChatType.PRIVATE.getNumber()) {
      output.writeEnum(2, chatType_);
    }
    if (fromId_ != null) {
      output.writeMessage(3, getFromId());
    }
    if (deliveryDateAfter_ != null) {
      output.writeMessage(4, getDeliveryDateAfter());
    }
    if (deliveryDateBefore_ != null) {
      output.writeMessage(5, getDeliveryDateBefore());
    }
    if (deliveryStatus_ != im.turms.turms.constant.MessageDeliveryStatus.READY.getNumber()) {
      output.writeEnum(6, deliveryStatus_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (size_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSize());
    }
    if (chatType_ != im.turms.turms.constant.ChatType.PRIVATE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, chatType_);
    }
    if (fromId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getFromId());
    }
    if (deliveryDateAfter_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getDeliveryDateAfter());
    }
    if (deliveryDateBefore_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getDeliveryDateBefore());
    }
    if (deliveryStatus_ != im.turms.turms.constant.MessageDeliveryStatus.READY.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
              .computeEnumSize(6, deliveryStatus_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return im.turms.turms.pojo.request.message.QueryMessagesRequestOuterClass.internal_static_im_turms_proto_QueryMessagesRequest_descriptor;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSize()) {
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getSize().hashCode();
    }
    hash = (37 * hash) + CHAT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + chatType_;
    if (hasFromId()) {
      hash = (37 * hash) + FROM_ID_FIELD_NUMBER;
      hash = (53 * hash) + getFromId().hashCode();
    }
    if (hasDeliveryDateAfter()) {
      hash = (37 * hash) + DELIVERY_DATE_AFTER_FIELD_NUMBER;
      hash = (53 * hash) + getDeliveryDateAfter().hashCode();
    }
    if (hasDeliveryDateBefore()) {
      hash = (37 * hash) + DELIVERY_DATE_BEFORE_FIELD_NUMBER;
      hash = (53 * hash) + getDeliveryDateBefore().hashCode();
    }
    hash = (37 * hash) + DELIVERY_STATUS_FIELD_NUMBER;
    hash = (53 * hash) + deliveryStatus_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static im.turms.turms.pojo.request.message.QueryMessagesRequest parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static im.turms.turms.pojo.request.message.QueryMessagesRequest parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static im.turms.turms.pojo.request.message.QueryMessagesRequest parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static im.turms.turms.pojo.request.message.QueryMessagesRequest parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static im.turms.turms.pojo.request.message.QueryMessagesRequest parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static im.turms.turms.pojo.request.message.QueryMessagesRequest parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static im.turms.turms.pojo.request.message.QueryMessagesRequest parseFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static im.turms.turms.pojo.request.message.QueryMessagesRequest parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static im.turms.turms.pojo.request.message.QueryMessagesRequest parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
  }

  public static im.turms.turms.pojo.request.message.QueryMessagesRequest parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static im.turms.turms.pojo.request.message.QueryMessagesRequest parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static im.turms.turms.pojo.request.message.QueryMessagesRequest parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(im.turms.turms.pojo.request.message.QueryMessagesRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  public static im.turms.turms.pojo.request.message.QueryMessagesRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
  internalGetFieldAccessorTable() {
    return im.turms.turms.pojo.request.message.QueryMessagesRequestOuterClass.internal_static_im_turms_proto_QueryMessagesRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                    im.turms.turms.pojo.request.message.QueryMessagesRequest.class, im.turms.turms.pojo.request.message.QueryMessagesRequest.Builder.class);
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof im.turms.turms.pojo.request.message.QueryMessagesRequest)) {
      return super.equals(obj);
    }
    im.turms.turms.pojo.request.message.QueryMessagesRequest other = (im.turms.turms.pojo.request.message.QueryMessagesRequest) obj;

    if (hasSize() != other.hasSize()) return false;
    if (hasSize()) {
      if (!getSize()
              .equals(other.getSize())) return false;
    }
    if (chatType_ != other.chatType_) return false;
    if (hasFromId() != other.hasFromId()) return false;
    if (hasFromId()) {
      if (!getFromId()
              .equals(other.getFromId())) return false;
    }
    if (hasDeliveryDateAfter() != other.hasDeliveryDateAfter()) return false;
    if (hasDeliveryDateAfter()) {
      if (!getDeliveryDateAfter()
              .equals(other.getDeliveryDateAfter())) return false;
    }
    if (hasDeliveryDateBefore() != other.hasDeliveryDateBefore()) return false;
    if (hasDeliveryDateBefore()) {
      if (!getDeliveryDateBefore()
              .equals(other.getDeliveryDateBefore())) return false;
    }
    if (deliveryStatus_ != other.deliveryStatus_) return false;
    return unknownFields.equals(other.unknownFields);
  }

  @java.lang.Override
  public im.turms.turms.pojo.request.message.QueryMessagesRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<QueryMessagesRequest>
          PARSER = new com.google.protobuf.AbstractParser<QueryMessagesRequest>() {
    @java.lang.Override
    public QueryMessagesRequest parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return new QueryMessagesRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<QueryMessagesRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<QueryMessagesRequest> getParserForType() {
    return PARSER;
  }

  /**
   * Protobuf type {@code im.turms.proto.QueryMessagesRequest}
   */
  public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:im.turms.proto.QueryMessagesRequest)
          im.turms.turms.pojo.request.message.QueryMessagesRequestOrBuilder {
    // Construct using im.turms.turms.pojo.request.message.QueryMessagesRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return im.turms.turms.pojo.request.message.QueryMessagesRequestOuterClass.internal_static_im_turms_proto_QueryMessagesRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return im.turms.turms.pojo.request.message.QueryMessagesRequestOuterClass.internal_static_im_turms_proto_QueryMessagesRequest_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      im.turms.turms.pojo.request.message.QueryMessagesRequest.class, im.turms.turms.pojo.request.message.QueryMessagesRequest.Builder.class);
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (sizeBuilder_ == null) {
        size_ = null;
      } else {
        size_ = null;
        sizeBuilder_ = null;
      }
      chatType_ = 0;

      if (fromIdBuilder_ == null) {
        fromId_ = null;
      } else {
        fromId_ = null;
        fromIdBuilder_ = null;
      }
      if (deliveryDateAfterBuilder_ == null) {
        deliveryDateAfter_ = null;
      } else {
        deliveryDateAfter_ = null;
        deliveryDateAfterBuilder_ = null;
      }
      if (deliveryDateBeforeBuilder_ == null) {
        deliveryDateBefore_ = null;
      } else {
        deliveryDateBefore_ = null;
        deliveryDateBeforeBuilder_ = null;
      }
      deliveryStatus_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return im.turms.turms.pojo.request.message.QueryMessagesRequestOuterClass.internal_static_im_turms_proto_QueryMessagesRequest_descriptor;
    }

    @java.lang.Override
    public im.turms.turms.pojo.request.message.QueryMessagesRequest getDefaultInstanceForType() {
      return im.turms.turms.pojo.request.message.QueryMessagesRequest.getDefaultInstance();
    }

    @java.lang.Override
    public im.turms.turms.pojo.request.message.QueryMessagesRequest build() {
      im.turms.turms.pojo.request.message.QueryMessagesRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public im.turms.turms.pojo.request.message.QueryMessagesRequest buildPartial() {
      im.turms.turms.pojo.request.message.QueryMessagesRequest result = new im.turms.turms.pojo.request.message.QueryMessagesRequest(this);
      if (sizeBuilder_ == null) {
        result.size_ = size_;
      } else {
        result.size_ = sizeBuilder_.build();
      }
      result.chatType_ = chatType_;
      if (fromIdBuilder_ == null) {
        result.fromId_ = fromId_;
      } else {
        result.fromId_ = fromIdBuilder_.build();
      }
      if (deliveryDateAfterBuilder_ == null) {
        result.deliveryDateAfter_ = deliveryDateAfter_;
      } else {
        result.deliveryDateAfter_ = deliveryDateAfterBuilder_.build();
      }
      if (deliveryDateBeforeBuilder_ == null) {
        result.deliveryDateBefore_ = deliveryDateBefore_;
      } else {
        result.deliveryDateBefore_ = deliveryDateBeforeBuilder_.build();
      }
      result.deliveryStatus_ = deliveryStatus_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof im.turms.turms.pojo.request.message.QueryMessagesRequest) {
        return mergeFrom((im.turms.turms.pojo.request.message.QueryMessagesRequest) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(im.turms.turms.pojo.request.message.QueryMessagesRequest other) {
      if (other == im.turms.turms.pojo.request.message.QueryMessagesRequest.getDefaultInstance()) return this;
      if (other.hasSize()) {
        mergeSize(other.getSize());
      }
      if (other.chatType_ != 0) {
        setChatTypeValue(other.getChatTypeValue());
      }
      if (other.hasFromId()) {
        mergeFromId(other.getFromId());
      }
      if (other.hasDeliveryDateAfter()) {
        mergeDeliveryDateAfter(other.getDeliveryDateAfter());
      }
      if (other.hasDeliveryDateBefore()) {
        mergeDeliveryDateBefore(other.getDeliveryDateBefore());
      }
      if (other.deliveryStatus_ != 0) {
        setDeliveryStatusValue(other.getDeliveryStatusValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      im.turms.turms.pojo.request.message.QueryMessagesRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (im.turms.turms.pojo.request.message.QueryMessagesRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.Int32Value size_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> sizeBuilder_;
    /**
     * <code>.google.protobuf.Int32Value size = 1;</code>
     * @return Whether the size field is set.
     */
    public boolean hasSize() {
      return sizeBuilder_ != null || size_ != null;
    }
    /**
     * <code>.google.protobuf.Int32Value size = 1;</code>
     * @return The size.
     */
    public com.google.protobuf.Int32Value getSize() {
      if (sizeBuilder_ == null) {
        return size_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : size_;
      } else {
        return sizeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int32Value size = 1;</code>
     */
    public Builder setSize(com.google.protobuf.Int32Value value) {
      if (sizeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        size_ = value;
        onChanged();
      } else {
        sizeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value size = 1;</code>
     */
    public Builder setSize(
        com.google.protobuf.Int32Value.Builder builderForValue) {
      if (sizeBuilder_ == null) {
        size_ = builderForValue.build();
        onChanged();
      } else {
        sizeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value size = 1;</code>
     */
    public Builder mergeSize(com.google.protobuf.Int32Value value) {
      if (sizeBuilder_ == null) {
        if (size_ != null) {
          size_ =
            com.google.protobuf.Int32Value.newBuilder(size_).mergeFrom(value).buildPartial();
        } else {
          size_ = value;
        }
        onChanged();
      } else {
        sizeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value size = 1;</code>
     */
    public Builder clearSize() {
      if (sizeBuilder_ == null) {
        size_ = null;
        onChanged();
      } else {
        size_ = null;
        sizeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value size = 1;</code>
     */
    public com.google.protobuf.Int32Value.Builder getSizeBuilder() {

      onChanged();
      return getSizeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int32Value size = 1;</code>
     */
    public com.google.protobuf.Int32ValueOrBuilder getSizeOrBuilder() {
      if (sizeBuilder_ != null) {
        return sizeBuilder_.getMessageOrBuilder();
      } else {
        return size_ == null ?
            com.google.protobuf.Int32Value.getDefaultInstance() : size_;
      }
    }
    /**
     * <code>.google.protobuf.Int32Value size = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>
        getSizeFieldBuilder() {
      if (sizeBuilder_ == null) {
        sizeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                getSize(),
                getParentForChildren(),
                isClean());
        size_ = null;
      }
      return sizeBuilder_;
    }

    private int chatType_ = 0;
    /**
     * <code>.im.turms.proto.ChatType chat_type = 2;</code>
     * @return The enum numeric value on the wire for chatType.
     */
    public int getChatTypeValue() {
      return chatType_;
    }
    /**
     * <code>.im.turms.proto.ChatType chat_type = 2;</code>
     * @param value The enum numeric value on the wire for chatType to set.
     * @return This builder for chaining.
     */
    public Builder setChatTypeValue(int value) {
      chatType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.im.turms.proto.ChatType chat_type = 2;</code>
     * @return The chatType.
     */
    public im.turms.turms.constant.ChatType getChatType() {
      @SuppressWarnings("deprecation")
      im.turms.turms.constant.ChatType result = im.turms.turms.constant.ChatType.valueOf(chatType_);
      return result == null ? im.turms.turms.constant.ChatType.UNRECOGNIZED : result;
    }
    /**
     * <code>.im.turms.proto.ChatType chat_type = 2;</code>
     * @param value The chatType to set.
     * @return This builder for chaining.
     */
    public Builder setChatType(im.turms.turms.constant.ChatType value) {
      if (value == null) {
        throw new NullPointerException();
      }

      chatType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.im.turms.proto.ChatType chat_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearChatType() {

      chatType_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Int64Value fromId_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> fromIdBuilder_;
    /**
     * <code>.google.protobuf.Int64Value from_id = 3;</code>
     * @return Whether the fromId field is set.
     */
    public boolean hasFromId() {
      return fromIdBuilder_ != null || fromId_ != null;
    }
    /**
     * <code>.google.protobuf.Int64Value from_id = 3;</code>
     * @return The fromId.
     */
    public com.google.protobuf.Int64Value getFromId() {
      if (fromIdBuilder_ == null) {
        return fromId_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : fromId_;
      } else {
        return fromIdBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int64Value from_id = 3;</code>
     */
    public Builder setFromId(com.google.protobuf.Int64Value value) {
      if (fromIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        fromId_ = value;
        onChanged();
      } else {
        fromIdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value from_id = 3;</code>
     */
    public Builder setFromId(
        com.google.protobuf.Int64Value.Builder builderForValue) {
      if (fromIdBuilder_ == null) {
        fromId_ = builderForValue.build();
        onChanged();
      } else {
        fromIdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value from_id = 3;</code>
     */
    public Builder mergeFromId(com.google.protobuf.Int64Value value) {
      if (fromIdBuilder_ == null) {
        if (fromId_ != null) {
          fromId_ =
            com.google.protobuf.Int64Value.newBuilder(fromId_).mergeFrom(value).buildPartial();
        } else {
          fromId_ = value;
        }
        onChanged();
      } else {
        fromIdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value from_id = 3;</code>
     */
    public Builder clearFromId() {
      if (fromIdBuilder_ == null) {
        fromId_ = null;
        onChanged();
      } else {
        fromId_ = null;
        fromIdBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value from_id = 3;</code>
     */
    public com.google.protobuf.Int64Value.Builder getFromIdBuilder() {

      onChanged();
      return getFromIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int64Value from_id = 3;</code>
     */
    public com.google.protobuf.Int64ValueOrBuilder getFromIdOrBuilder() {
      if (fromIdBuilder_ != null) {
        return fromIdBuilder_.getMessageOrBuilder();
      } else {
        return fromId_ == null ?
            com.google.protobuf.Int64Value.getDefaultInstance() : fromId_;
      }
    }
    /**
     * <code>.google.protobuf.Int64Value from_id = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>
        getFromIdFieldBuilder() {
      if (fromIdBuilder_ == null) {
        fromIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                getFromId(),
                getParentForChildren(),
                isClean());
        fromId_ = null;
      }
      return fromIdBuilder_;
    }

    private com.google.protobuf.Int64Value deliveryDateAfter_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> deliveryDateAfterBuilder_;
    /**
     * <code>.google.protobuf.Int64Value delivery_date_after = 4;</code>
     * @return Whether the deliveryDateAfter field is set.
     */
    public boolean hasDeliveryDateAfter() {
      return deliveryDateAfterBuilder_ != null || deliveryDateAfter_ != null;
    }
    /**
     * <code>.google.protobuf.Int64Value delivery_date_after = 4;</code>
     * @return The deliveryDateAfter.
     */
    public com.google.protobuf.Int64Value getDeliveryDateAfter() {
      if (deliveryDateAfterBuilder_ == null) {
        return deliveryDateAfter_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : deliveryDateAfter_;
      } else {
        return deliveryDateAfterBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int64Value delivery_date_after = 4;</code>
     */
    public Builder setDeliveryDateAfter(com.google.protobuf.Int64Value value) {
      if (deliveryDateAfterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        deliveryDateAfter_ = value;
        onChanged();
      } else {
        deliveryDateAfterBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value delivery_date_after = 4;</code>
     */
    public Builder setDeliveryDateAfter(
        com.google.protobuf.Int64Value.Builder builderForValue) {
      if (deliveryDateAfterBuilder_ == null) {
        deliveryDateAfter_ = builderForValue.build();
        onChanged();
      } else {
        deliveryDateAfterBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value delivery_date_after = 4;</code>
     */
    public Builder mergeDeliveryDateAfter(com.google.protobuf.Int64Value value) {
      if (deliveryDateAfterBuilder_ == null) {
        if (deliveryDateAfter_ != null) {
          deliveryDateAfter_ =
            com.google.protobuf.Int64Value.newBuilder(deliveryDateAfter_).mergeFrom(value).buildPartial();
        } else {
          deliveryDateAfter_ = value;
        }
        onChanged();
      } else {
        deliveryDateAfterBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value delivery_date_after = 4;</code>
     */
    public Builder clearDeliveryDateAfter() {
      if (deliveryDateAfterBuilder_ == null) {
        deliveryDateAfter_ = null;
        onChanged();
      } else {
        deliveryDateAfter_ = null;
        deliveryDateAfterBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value delivery_date_after = 4;</code>
     */
    public com.google.protobuf.Int64Value.Builder getDeliveryDateAfterBuilder() {

      onChanged();
      return getDeliveryDateAfterFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int64Value delivery_date_after = 4;</code>
     */
    public com.google.protobuf.Int64ValueOrBuilder getDeliveryDateAfterOrBuilder() {
      if (deliveryDateAfterBuilder_ != null) {
        return deliveryDateAfterBuilder_.getMessageOrBuilder();
      } else {
        return deliveryDateAfter_ == null ?
            com.google.protobuf.Int64Value.getDefaultInstance() : deliveryDateAfter_;
      }
    }
    /**
     * <code>.google.protobuf.Int64Value delivery_date_after = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>
        getDeliveryDateAfterFieldBuilder() {
      if (deliveryDateAfterBuilder_ == null) {
        deliveryDateAfterBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                getDeliveryDateAfter(),
                getParentForChildren(),
                isClean());
        deliveryDateAfter_ = null;
      }
      return deliveryDateAfterBuilder_;
    }

    private com.google.protobuf.Int64Value deliveryDateBefore_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> deliveryDateBeforeBuilder_;
    /**
     * <code>.google.protobuf.Int64Value delivery_date_before = 5;</code>
     * @return Whether the deliveryDateBefore field is set.
     */
    public boolean hasDeliveryDateBefore() {
      return deliveryDateBeforeBuilder_ != null || deliveryDateBefore_ != null;
    }
    /**
     * <code>.google.protobuf.Int64Value delivery_date_before = 5;</code>
     * @return The deliveryDateBefore.
     */
    public com.google.protobuf.Int64Value getDeliveryDateBefore() {
      if (deliveryDateBeforeBuilder_ == null) {
        return deliveryDateBefore_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : deliveryDateBefore_;
      } else {
        return deliveryDateBeforeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int64Value delivery_date_before = 5;</code>
     */
    public Builder setDeliveryDateBefore(com.google.protobuf.Int64Value value) {
      if (deliveryDateBeforeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        deliveryDateBefore_ = value;
        onChanged();
      } else {
        deliveryDateBeforeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value delivery_date_before = 5;</code>
     */
    public Builder setDeliveryDateBefore(
        com.google.protobuf.Int64Value.Builder builderForValue) {
      if (deliveryDateBeforeBuilder_ == null) {
        deliveryDateBefore_ = builderForValue.build();
        onChanged();
      } else {
        deliveryDateBeforeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value delivery_date_before = 5;</code>
     */
    public Builder mergeDeliveryDateBefore(com.google.protobuf.Int64Value value) {
      if (deliveryDateBeforeBuilder_ == null) {
        if (deliveryDateBefore_ != null) {
          deliveryDateBefore_ =
            com.google.protobuf.Int64Value.newBuilder(deliveryDateBefore_).mergeFrom(value).buildPartial();
        } else {
          deliveryDateBefore_ = value;
        }
        onChanged();
      } else {
        deliveryDateBeforeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value delivery_date_before = 5;</code>
     */
    public Builder clearDeliveryDateBefore() {
      if (deliveryDateBeforeBuilder_ == null) {
        deliveryDateBefore_ = null;
        onChanged();
      } else {
        deliveryDateBefore_ = null;
        deliveryDateBeforeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value delivery_date_before = 5;</code>
     */
    public com.google.protobuf.Int64Value.Builder getDeliveryDateBeforeBuilder() {

      onChanged();
      return getDeliveryDateBeforeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int64Value delivery_date_before = 5;</code>
     */
    public com.google.protobuf.Int64ValueOrBuilder getDeliveryDateBeforeOrBuilder() {
      if (deliveryDateBeforeBuilder_ != null) {
        return deliveryDateBeforeBuilder_.getMessageOrBuilder();
      } else {
        return deliveryDateBefore_ == null ?
            com.google.protobuf.Int64Value.getDefaultInstance() : deliveryDateBefore_;
      }
    }
    /**
     * <code>.google.protobuf.Int64Value delivery_date_before = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>
        getDeliveryDateBeforeFieldBuilder() {
      if (deliveryDateBeforeBuilder_ == null) {
        deliveryDateBeforeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                getDeliveryDateBefore(),
                getParentForChildren(),
                isClean());
        deliveryDateBefore_ = null;
      }
      return deliveryDateBeforeBuilder_;
    }

    private int deliveryStatus_ = 0;
    /**
     * <code>.im.turms.proto.MessageDeliveryStatus delivery_status = 6;</code>
     * @return The enum numeric value on the wire for deliveryStatus.
     */
    public int getDeliveryStatusValue() {
      return deliveryStatus_;
    }
    /**
     * <code>.im.turms.proto.MessageDeliveryStatus delivery_status = 6;</code>
     * @param value The enum numeric value on the wire for deliveryStatus to set.
     * @return This builder for chaining.
     */
    public Builder setDeliveryStatusValue(int value) {
      deliveryStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.im.turms.proto.MessageDeliveryStatus delivery_status = 6;</code>
     * @return The deliveryStatus.
     */
    public im.turms.turms.constant.MessageDeliveryStatus getDeliveryStatus() {
      @SuppressWarnings("deprecation")
      im.turms.turms.constant.MessageDeliveryStatus result = im.turms.turms.constant.MessageDeliveryStatus.valueOf(deliveryStatus_);
      return result == null ? im.turms.turms.constant.MessageDeliveryStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.im.turms.proto.MessageDeliveryStatus delivery_status = 6;</code>
     * @param value The deliveryStatus to set.
     * @return This builder for chaining.
     */
    public Builder setDeliveryStatus(im.turms.turms.constant.MessageDeliveryStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }

      deliveryStatus_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.im.turms.proto.MessageDeliveryStatus delivery_status = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeliveryStatus() {

      deliveryStatus_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:im.turms.proto.QueryMessagesRequest)
  }

}

